### ISSUE TITLE
tileset.json properties section

### ISSUE THREAD

**Issue by jbo023** [CesiumGS/3d-tiles#157]
Hi, 

we are using the properties section in the tileset.json to store meta data for the dataset. 
While working with the spec we had several questions. 

- is it possible to extent the specification to also support nested attributes (JSONObjects) for example with the following syntax ?

``` 
"properties": {
    "Address": {
      "properties": {
        "city":{},
        "street":{},
        "housenumber":{}
      }      
    }
  }
```
- we would think that a datatype maybe useful.
``` 
"properties": {
    "Height": {
      "type": Number,
      "minimum":0,
      "maximum":200
    }
  }
```

What do you think about these additions ?

Jannes

**Comment by lilleyse** [comment]
> is it possible to extent the specification to also support nested attributes (JSONObjects) for example with the following syntax ?

This would be convenient to have, but my main worry with this method is that the JSON objects may have different definitions so it is not safe to say that every feature has a `city` or `street` sub-property. In the case that every feature does contain the same object structure it would work, but then it would make more sense to use arrays of properties instead.

> we would think that a datatype maybe useful.

This could be nice to have, especially for properties where min/max don't make sense (like strings, objects, arrays)

**Comment by lilleyse** [comment]
Some more ideas about the "type" property:

Possible types:
```
object
array
number
string
boolean
vec2
vec3
vec4
```


* Should `type` be optional? Array elements may not be the same type.
* `minimum` and `maximum` only apply to `number`. Should they always be optional?
    * What about component-wise `minimum` and `maximum` for `vec2`, `vec3`, and `vec4`?
* `number` is used when the property is a `SCALAR` binary property.
* What other info would be useful to have?

**Comment by pjcozzi** [comment]
Let's scope this as small as possible for 3D Tiles 1.0 and borrow from glTF as much as we can - however, the types here are more broad given strings, etc.

Also, let's rely on `extras` for storing anything really complex and revisit, if needed, post 1.0.

CC #8

**Comment by pjcozzi** [comment]
To scope 1.0, let's rely on `extras`, #8, and add this post 1.0 as needed.

**Comment by ptrgags** [comment]
The new [3DTILES_metadata](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata) extension provide most of this functionality:

* [Tileset Metadata](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata#tileset-properties) allows more structured metadata at the tileset level (albeit no nested properties)
* [Statistics](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata#statistics) can be used for storing aggregate stats about metadata such as min/max/average
