### ISSUE TITLE
Support arbitrary-length values on the batch table binary body

### ISSUE THREAD

**Issue by ibesora** [CesiumGS/3d-tiles#161]
I'm sorry if it has been asked or dismissed before, I've taken a look at the open and closed issues and it seems none addresses what I want.
I'm creating a b3dm from a geoJSON which has some attributes (numeric and string) and I want to store them on the binary body of the batch table. 
Could it be possible to create a new componentType with a parameter to specify its byte lenght? That way you would be able to store arbitrary data in the binary body, without having to use the JSON header and reducing the final size.

**Comment by lilleyse** [comment]
The reduced JSON portion would be a plus, but I can't think of a way for an implementation to parse the binary body without having some knowledge about the componentType. Maybe an app-specific batch table loader could understand the chunk of binary data, but I don't feel as if this a common case. Let me know if I'm missing any ideas here.

**Comment by pjcozzi** [comment]
@ibesora if you have a concrete proposal, we are interested in hearing it.

@lilleyse long-term, post 1.0, I don't think the custom batch table is out of the question.

**Comment by pjcozzi** [comment]
I think this will be resolved with #457

**Comment by pjcozzi** [comment]
Also: https://github.com/CesiumGS/glTF/pull/4

**Comment by lilleyse** [comment]
We considered adding a `BLOB` type to the 3D Metadata Specification which would allow for separate byte lengths per value. We could revisit this in the future.
