### ISSUE TITLE
Hints for culling optimizations

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#176]
Potentially add optimization hints (like culling with children BVs instead of the parent) so the runtime doesn't have to figure out if the optimization is a good idea (e.g., by computing the volume of the children BV).  See https://github.com/AnalyticalGraphicsInc/cesium/pull/4978/

Could be useful per-tile, but would be cleaner to do per tileset, and then tilesets of tilesets could be used if needed.

The spec would also allow this to be ignored; exporters do not need to write it, and runtimes do not need to consider it.

@austinEng

**Comment by austinEng** [comment]
If no hints are given, the runtime could also compute these hints on tileset load, correct? It doesn't require loading any actual tile content.

**Comment by pjcozzi** [comment]
> If no hints are given, the runtime could also compute these hints on tileset load, correct? 

Yeap.

**Comment by lilleyse** [comment]
See runtime example of this optimization in CesiumJS: https://github.com/CesiumGS/cesium/pull/4978

These types of culling hints could be stored in tile metadata with new semantics.
