### ISSUE TITLE
Allow storing point clouds in other coordinate systems

### ISSUE THREAD

**Issue by SunBlack** [CesiumGS/3d-tiles#210]
Currently point clouds are always stored as Cartesian coordinates - but currently I need distance from any point to the ellipsoid. So there exists currently 3 possible ways to do it:
- Convert Cartesian back to Cartographic on GPU => expensive
- Store height in batch table => increase transfer size with a duplicated information
- Store points as Cartographic coordinates => Need to transform coordinates in GPU to Cartesian
- Convert Cartesian back to Cartographic on CPU => only 1-Time calculation on JS side, but not sure how fast it is

Currently I prefer third option, because we got another benefit of this option: Most point clouds are stored in a local metric coordinate system (like ETRS89), so in case of a 2.5D point cloud points have a fixed distance between each other. This is perfect to store them quantized. But because of transformation to Cartesian it is hard to calculate a good scale factor (which was easy before).

**Comment by lilleyse** [comment]
Thanks for laying all the options out. None of the options strikes me as a clear winner but point 2 is the easiest to use at the moment.

1. I think this would be the easiest future thing to handle assuming a fast GLSL implementation of `cartesianToCartographic` that could potentially be added to the styling language as an extension.
2.  Yeah this is a trade-off of being the highest transfer cost but the fastest speed.
3. I'm a little hesitant about this since all other units in 3D Tiles are Cartesian. This also has a similar cost to point 1.
4. This is a pretty heavy operation at processing time, but would cut down on the performance issues of point 1. This would also add to the GPU memory cost, equal to point 2.

**Comment by SunBlack** [comment]
> I think this would be the easiest future thing to handle assuming a fast GLSL implementation of cartesianToCartographic that could potentially be added to the styling language as an extension.

Well but there is no guaranty that all WEBGL implementation can run this, because of this part of [WebGL 1.0 spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/) (I had already trouble with this some years ago with chrome/firefox)

> A WebGL implementation must only accept shaders which conform to The OpenGL ES Shading Language, Version 1.00 [GLES20GLSL], and which do not exceed the minimum functionality mandated in Sections 4 and 5 of Appendix A. In particular:
> * while and do-while loops are disallowed, since they are optional in Appendix A.

>I'm a little hesitant about this since all other units in 3D Tiles are Cartesian. This also has a similar cost to point 1.

You are not accessing position outside of shader, so it should only related to `PointCloud3DTileContent`, or? So I don't believe its need many adjustments. And performance of  `cartographicToCartesian` 
 should be much better in glsl than `cartesianToCartographic`, because we have only 2x sin and cos instead of a loop.

In general there exists more good compression beyond quantized positions which we could support - so maybe we it is better to implement a Extension-API to parse and interpret content.

**Comment by macneille** [comment]
@SunBlack , I am interested to know which option you ended up choosing.  I have a similar use case in which I need to display "slices" of a point cloud based on the distance from each point to the ellipsoid.  Any advice you have is much appreciated.

**Comment by ptrgags** [comment]
in CesiumJS, we're considering providing cartographic coordinates within the new `CustomShader` to make it available in a GLSL callback, see https://github.com/CesiumGS/cesium/issues/9735.

I'm closing this issue since we want to handle this in the client rather than the spec.
