### ISSUE TITLE
Allow additional vector image storing options

### ISSUE THREAD

**Issue by bagnell** [CesiumGS/3d-tiles#239]
From https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/228#discussion_r120611000 : 

* Point to a subset of some payload like `buffer`/`bufferView` in glTF.
* Have an atlas as part of the payload and the image be a subregion of the atlas.

**Comment by lilleyse** [comment]
Added to https://github.com/CesiumGS/3d-tiles/issues/2#issuecomment-969148373
