### ISSUE TITLE
3D Tiles Next roadmap

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#247]
Now that the Cesium 3D Tiles implementation is officially shipping in Cesium 1.35, we would like community input on the big picture for the next version of 3D Tiles:

**3D Tiles Next**.

A key part of 3D Tiles' success thus far has been the active community participation, thank you!  We are striving to increase it for **3D Tiles Next** so any and all feedback is welcome!

Our vision includes:

* **A truly 3D vector tile for heterogeneous classification** that conforms to arbitrary 3D tilesets such as terrain, photogrammetry models, and point clouds. #228, #25, #239
* **Time-dynamic streaming** - basically streaming video meets massive 3D geospatial datasets, except the video is _interactive_. #102
* **A 3D analytics-enabled styling language** - is a feature in shadow? visible from another feature? what is the distance to another feature? etc. #2
* **Fast compression/decompression** for geometry and textures. #188, #173
* **Implicit tiling schemes** to better support dynamically generated tilesets, uniform global-scale datasets, and time-dynamic datasets. #92, #90
* **An even more engaged community and ecosystem**, including [Cesium Composer](https://www.cesium.com/)

Please comment with your ideas, feedback, or even just +1's for items of interest.

For more background, see the [The Next Generation of 3D Tiles](http://cesiumjs.org/2017/07/12/The-next-generation-of-3D-Tiles/) blog post.

**Comment by lilleyse** [comment]
An ambitious list for sure. It's nice to see vector tiles getting closer, which is really the start for all the analytical styling to come.

Another area that we've discussed previously but is not included here is whether terrain/imagery deserves its own 3D Tiles format, or whether it can be served adequately by b3dm.

**Comment by pjcozzi** [comment]
Terrain is getting good mileage with `b3dm`, but we can likely do better with a custom format with terrain-specific compression and less boilerplate.  It should become more clear as we see how Draco does.

**Comment by pjcozzi** [comment]
Topic  | Status
---|---
[Vector Data](TileFormats/VectorData/README.md) (*.vctr) _Polygons, polylines, and placemarks_ | :white_circle: **In progress**, [#124](https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/124/files)
Terrain v2  | :white_circle: **Not started**, [quantized-mesh](https://cesiumjs.org/data-and-assets/terrain/formats/quantized-mesh-1.0.html) is a good starting point; in the meantime, folks are using [Batched 3D Model](TileFormats/Batched3DModel/README.md)
[OpenStreetMap](TileFormats/OpenStreetMap/README.md)  | :white_circle: **Not started** Currently folks are using [Batched 3D Model](TileFormats/Batched3DModel/README.md)
Stars  | :white_circle: **Not started**

**Comment by NatKov** [comment]
May I please ask if there is an expected date for 3d vector tiles release?

**Comment by lilleyse** [comment]
There isn't a release date yet can start experimenting with vector tiles now. The Vector Data format is outlined [here](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next/TileFormats/VectorData) and Cesium has experimental support, like this [Terrain Classification](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Terrain%20Classification.html&label=3D%20Tiles) demo.

**Comment by tberendes** [comment]
I have been looking over the Geometry tile format in the 3d-tiles-next branch, and I would like to start experimenting with it.  Is there support in the 1.48 release yet?

**Comment by lilleyse** [comment]
@tberendes - Yes, Cesium has experimental support for Geometry Tiles. Right now they can only be used to classify other tilesets and are not rendered as solid shapes.

See the [Point Cloud Classification](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Point%20Cloud%20Classification.html) demo.

**Comment by tberendes** [comment]
Thanks for your quick response!  Are there plans for independent solid shape rendering?  I would like to be able to use a 3d tile format to display solid (with transparency) geometric shapes (cylinders and cubes,  and possibly arbitrary shapes).  We are trying to render large volumes of 3D radar data and found that using entities provides a better visual than pointcloud, but runs the browser out of memory quickly.  We were wondering if Geometry or Vector tiles might be the way to go in the future.

**Comment by lilleyse** [comment]
We don't have plans for it at the moment but I opened an issue so we can keep track of it: https://github.com/AnalyticalGraphicsInc/cesium/issues/6919.

If you're looking to do instanced arbitrary shapes you might also want to check out [Instanced3DModels](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/TileFormats/Instanced3DModel).

**Comment by tberendes** [comment]
Ok, thanks for the info.  I had looked at the Instanced3DModel, but the creation of the models seems daunting, and overkill for what we need.  We want to generate our shapes on the fly, and I'm not sure how you would do that using the models.

**Comment by ptrgags** [comment]
This issue is outdated, the current state of 3D Tiles Next can be found here: https://github.com/CesiumGS/3d-tiles/tree/main/next
