### ISSUE TITLE
Consider adding mutables to styling language

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#252]
via @SunBlack:

```json
{
    "mutables" : {
        "lengthFactor" : { type: "float", value: 0.1 },
        "idFactor" : { type: "int", value: 5 }
    },
    "defines" : {
        "length" : "length(${POSITION})",
        "time" : "${tiles3d_tileset_time} * 0.1"
    },
    "color" : {
        "conditions" : [
            ["${length} < ${lengthFactor}", "${length} * color('red')"],
            ["${length} < 5 * ${lengthFactor}", "vec4(vec3(${temperature} * fract(${time})), 1.0)"],
            ["${id} < 150 * ${idFactor}", "vec4(${secondaryColor} / 5.0, 1.0)"],
            ["${id} < 200 * ${idFactor}", "rgb(0, 0, Number(${secondaryColor}.x < 0.5) * 255)"]
        ]
    },
    "show" : "${length} < 0.9"
}
```

Full discussion: https://github.com/AnalyticalGraphicsInc/cesium/pull/5380#issuecomment-305167153

**Comment by lilleyse** [comment]
A CesiumJS implementation was started in https://github.com/AnalyticalGraphicsInc/cesium/pull/5380. The code is parked at [Cesium3DTileStyle_uniform_support](https://github.com/AnalyticalGraphicsInc/cesium/tree/Cesium3DTileStyle_uniform_support).

**Comment by lilleyse** [comment]
CesiumJS has custom shaders which may be a better approach.

May also be considered for future styling language updates: https://github.com/CesiumGS/3d-tiles/issues/2#issuecomment-969150826
