### ISSUE TITLE
Make alpha its own property in the styling language

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#266]
Would it be worthwhile to add an "alpha" property? This would give more flexibility for complex styles where the alpha is treated differently than color.

One example: color by groups but set alpha to be smooth.

```json
{
    "color": {
        "conditions": [
            ["${height} < 100", "color('red')"],
            ["${height} < 200", "color('green')"],
            ["${height} < 300", "color('blue')"],
            ["true", "color('yellow')"]
        ]
    },
    "alpha": "mix(0.0, 1.0, min(${height} / 300, 1.0))"
}
```

**Comment by likangning93** [comment]
how *Iron Man* could we *Iron Man*?

**Comment by pjcozzi** [comment]
I thought about doing this at one point - I might have even done it in the first prototype, but there's no discussion in #2.  @ggetz do you recall?

@lilleyse concretely, what do you propose:
```
color : rgb
alpha : a
```
or
```
color : rgba
alpha : a // overrides color.a
```
or something else?

**Comment by ggetz** [comment]
I think there was some brief discussion, but it was put on the back burner since transparency could be accomplished with rgba. I see no reason why not, css has it's own `opacity` property in addition to rgba.

**Comment by lilleyse** [comment]
I would prefer the override method.

**Comment by pjcozzi** [comment]
Override is OK with me.

Could be scoped 1.0 or post 1.0.

**Comment by pjcozzi** [comment]
Since this can be done in a backwards compatible way, pushing post 1.0.

**Comment by lilleyse** [comment]
Noted in https://github.com/CesiumGS/3d-tiles/issues/2#issuecomment-969154251
