### ISSUE TITLE
Expose ${BATCH_ID} as a built-in variable for the styling language

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#268]
The shading language could support a built-in variable `${BATCH_ID}` that returns the feature's batch id. This is similar to how point clouds have `${POSITION}`, `${COLOR)`, and `$(NORMAL)` for getting the point's internal attributes. `${BATCH_ID}` would work for any tile type.

This isn't a critical thing to add, it's mainly a convenience.

**Comment by pjcozzi** [comment]
Labeled `next`; not needed for `1.0`.

**Comment by lilleyse** [comment]
Noted in https://github.com/CesiumGS/3d-tiles/issues/2#issuecomment-969155597
