### ISSUE TITLE
More flexible styling for classified point clouds

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#269]
If a point cloud is classified, in that it uses batch ids and has a `BATCH_LENGTH`, the length of each batch table array is equal to `BATCH_LENGTH` rather than `POINTS_LENGTH`. This means it is not possible to support per-point attributes when the point cloud is classified. Styling based on a point's "intensity" or "height" isn't possible.

The change would require marking some batch table properties as per-batch properties and others as per-point properties.

**Comment by pjcozzi** [comment]
Are you certain this would be part of a MVP 1.0?

If it doesn't affect basically all point cloud styling and can be added in a backwards-compatible way, it should be labeled `next` to reduce scope.

**Comment by lilleyse** [comment]
It isn't required for 1.0. Any app can get around this limitation by storing classification as a per-point property, however it's more work to get the same functionality. Probably best to scope for `next`.

**Comment by lilleyse** [comment]
See https://github.com/CesiumGS/glTF/pull/1 - per-point and per-group properties can be specified together by using multiple batch tables.

**Comment by pjcozzi** [comment]
CC https://github.com/CesiumGS/glTF/pull/4

**Comment by ptrgags** [comment]
This is now possible with the `EXT_mesh_features` extension for glTF: https://github.com/KhronosGroup/glTF/pull/2082. We allow multiple sets of feature ID attributes. See [the Feature ID section](https://github.com/CesiumGS/glTF/blob/proposal-EXT_mesh_features/extensions/2.0/Vendor/EXT_mesh_features/README.md#feature-ids) of the spec
