### ISSUE TITLE
Evaluate Google FlatBuffers

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#270]
https://github.com/google/flatbuffers

"Next gen protocol buffers"

At some point, is this valuable to parts of 3D Tiles?

**Comment by pjcozzi** [comment]
@lilleyse what do you think?  Not of interest?  OK to close?

**Comment by lilleyse** [comment]
Not actionable right now so ok to close. But if we ever want to serialize objects like tileset.json in a more compact way we could start looking more at protobuffers or flatbuffers.

As a side note, Apache Arrow uses flatbuffers as a way to serialize schemas.
