### ISSUE TITLE
Clean up 3d-tiles-next branch

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#328]
The [3d-tiles-next](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/3d-tiles-next) branch is still based  on the pre-1.0 spec and doesn't include many of the organizational fixes made for the 1.0 branch.

The Vector Tile and Geometry Tile pages should be updated to follow the other tile formats more closely.

**Comment by pjcozzi** [comment]
@lilleyse is this OBE?

**Comment by lilleyse** [comment]
Yes, no action here.

The old vector tile format and geometry tile format are now on the [vctr](https://github.com/CesiumGS/3d-tiles/tree/vctr) branch.
