### ISSUE TITLE
Allow tileset transform to scale geometric error

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#367]
The tileset transform should be able to scale geometric error. The two areas in the spec that need to be revised are:

In `specification/README.md`
> The transform property does not apply to geometricError—i.e., the scale defined by transform does not scale the geometric error—the geometric error is always defined in meters.

In `tile.schema.json`:
> transform does not apply to geometricError

In CesiumJS, see https://github.com/AnalyticalGraphicsInc/cesium/issues/5330 and https://github.com/AnalyticalGraphicsInc/cesium/pull/7411

**Comment by pjcozzi** [comment]
This is a spec bug fix, please coordinate with @ggetz to see if it can go into the OGC Community Standard; otherwise, this needs to be versioned draft 1.0.1.

**Comment by ggetz** [comment]
This would need to go in v1.0.1

**Comment by javagl** [comment]
<sup>I think it was said to become an own issue, but it may make (more?) sense to just mention this here)</sup>

When the tileset scaling is supposed to affect the `geometricError`, then it has to be clarified which scaling factor should be used in the case of non-uniform scalings (even though non-uniform scalings are probably rare in practice). Saying that the _maximum_ of the three scaling factors should be used may be a sensible, conservative solution here.

**Comment by ptrgags** [comment]
@javagl good point about the non-uniform scaling, though if the matrix has both rotation and scaling, you really need to do a [principal component analysis](https://www.wikiwand.com/en/Principal_component_analysis) or [Singular value decomposition](https://www.wikiwand.com/en/Singular_value_decomposition) to align the scaling factors with the axes. 

I'm working on a PR for this, albeit finding the right way to describe this might get tricky
