### ISSUE TITLE
Clarify direction of forward/up

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/3d-tiles#372]
This [came up on the forum](https://groups.google.com/d/msg/cesium-dev/bKQUKpcxoiE/wxUC5iYsBgAJ). There's some confusion regarding the axes for Instanced 3D Models. The spec says:

> 3D Tiles defines the z axis as up for local Cartesian coordinate systems

From https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#coordinate-reference-system-crs

But then in the i3dm section:

> ... the y vector maps to the up vector. The z vector would map to a forward vector ...

From https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/TileFormats/Instanced3DModel#instance-orientation

From my offline discussion with @lilleyse it sounds like the right answer is that z is up, and the right direction is defined by the implementer/engine. So perhaps we should:

* Add a note about forward/right in the `coordinate-reference-system-crs` section
* Clarify that the i3dm section is actually just an example of how a given coordinate system will be transformed for the i3dm model?

**Comment by lilleyse** [comment]
Closing as duplicate with #504
