### ISSUE TITLE
Vctr format: feature table dos not have "BATCH_LENGTH" field

### ISSUE THREAD

**Issue by rainliang000** [CesiumGS/3d-tiles#379]
Currently, every polygon/polyline/point has a feature properties, it is costly somehow. 
I think we need add "BATCH_LENGTH" field to feature table to identify the feature length. Then we can make some polygons or polylines belong to one batchid. 
Also the b3dm format already has a "BATCH_LENGTH" field in its feature table.

// current code from Vector3DTileContent.js line 325-330
var numberOfPolygons = defaultValue(featureTableJson.POLYGONS_LENGTH, 0);
..
var totalPrimitives = numberOfPolygons + numberOfPolylines + numberOfPoints;
var batchTable = new Cesium3DTileBatchTable(content, totalPrimitives, batchTableJson, batchTableBinary, createColorChangedCallback(content));

**Comment by jbo023** [comment]
Ho, we are also really interested in this topic.

At the moment it is not possible to group Features in MultiGeometries. 
The proposed change to use BATCH_LENGTH instead of the calculated property totalPrimitives sounds like a good solution?

**Comment by OmarShehata** [comment]
Thanks for the suggestion! The vector tiles format is still a draft, I've labelled this as "vector data" to make sure this use case is considered when there's more progress on the standard. You can also watch the vector tiles roadmap here: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/25

**Comment by lilleyse** [comment]
Yes this is an omission in the old vctr spec. This will be handled properly in a future vector tile format CC #25
