### ISSUE TITLE
tilesetVersion and external tilesets

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#381]
The spec should be more clear about the interaction between `asset.tilesetVersion` and external tilesets. Do external tilesets always use their parent's `tilesetVersion`? Can an external tileset override it by using a different `tilesetVersion`? Or is this completely implementation specific?

CC https://github.com/AnalyticalGraphicsInc/cesium/pull/8108

**Comment by ptrgags** [comment]
Talked about this with @lilleyse and @pjcozzi, this should be clarified so that the child tileset's `tilesetVersion` will override that of the parent's. 

I'll put in a PR for this later today.
