### ISSUE TITLE
Support glTF and glb as tile formats

### ISSUE THREAD

**Issue by FreakTheMighty** [CesiumGS/3d-tiles#385]
I would like to propose extending the [tile format specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tile-format-specifications) to support glTF or glb files as tile formats.

While batching via a b3dm is a useful optimization, simply tiling a model without batching provides benefits as well. Additionally, as there is no requirement that the glb contained in the b3dm is actually batched, it adds complexity without actually enforcing this particular optimization.

---
The benefits that I see for supporting non-batched tiles include:
* More simple tile generation. It is easier to leverage the glTF ecosystem than it is to generate a B3DM.
* Not all runtimes support vertex attributes (Maybe its just Unity that doesn't, but still). Without custom vertex attributes, it makes achieving object level selection difficult.
*  Non-batched models may preserve their source hierarchy allowing client applications to find the exact transform of a particular node. Again, while it's possible to leave a non-batched glb within a B3DM, it seems like added complexity without the performance benefit.

**Comment by pjcozzi** [comment]
@FreakTheMighty agreed.  We plan to do this.  We may also create some glTF extensions along with the glTF community, e.g., for the Batch Table, point cloud compression and attributes, instancing, etc. so that glTF can be used directly from 3D Tiles - and when used with the these extensions, you would have  the same capability of using b3dm, i3dm, and pnts.

**Comment by FreakTheMighty** [comment]
@pjcozzi that sounds great! It hadn't occurred to me that the other formats might be achievable through a glTF extension.

Is this work captured in any other ticket or pull request?

**Comment by AnthonyCorrado** [comment]
@pjcozzi do you have any timetable for the glTF support? This would greatly benefit our current project, as well.

**Comment by pjcozzi** [comment]
@FreakTheMighty there isn't another issue for this yet, but there will be an issue or pull request in this repo when ready.

@AnthonyCorrado I don't have a timeline but it will likely be within the next 6 months.  I would suggest starting with the current version as updating will be straightforward.

**Comment by zhangqun23** [comment]
Is batch display GLTF currently implemented?This would greatly benefit our current project, as well.Thank you

**Comment by lilleyse** [comment]
@FreakTheMighty  @AnthonyCorrado There's an early draft of moving b3dm/pnts to glTF here: https://github.com/CesiumGS/glTF/pull/1.

**Comment by pjcozzi** [comment]
CC https://github.com/CesiumGS/glTF/pull/4

**Comment by ptrgags** [comment]
This is now supported with the `3DTILES_content_gltf` extension: https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf
