### ISSUE TITLE
[Question] Any python library to convert geometries to 3d tiles 

### ISSUE THREAD

**Issue by am2222** [CesiumGS/3d-tiles#389]
Hi,
I was wondering if there is any python library to convert simple geometries  (polygon, line and points) to 3d tile format to be able to use in cesium,
I think this seems to be something similar to the vector tiles but since cesium does not support that so I was wondering to convert simple shapes to 3d vector tiles and work with them

**Comment by lilleyse** [comment]
Sorry for the late reply @am2222, but this question is probably better for the [Cesium Forum](https://community.cesium.com/).
