### ISSUE TITLE
Is it possible to add or modify the batchtable in a b3dm file? 

### ISSUE THREAD

**Issue by yangtian62** [CesiumGS/3d-tiles#390]
I'm wondering if I set a batch id inside the batch tabel for each b3dm, it could be highlighted when mouse moving over. To show all b3dms with the same batch id. Like the Cesium3DTileFeature.

**Comment by lilleyse** [comment]
@yangtian62 Sorry for the late reply but this might be a better question for the [Cesium Forum](https://community.cesium.com/).
