### ISSUE TITLE
Conflict in Positions for Feature Table

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/3d-tiles#396]
According to https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/FeatureTable/README.md#json-header, the feature table may contain arrays with property values directly. The example given there is that of the `POSITION` attribute for Instanced 3D Models.

However, https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/Instanced3DModel/README.md#instance-semantics says
> The value for each instance semantic must be a reference to the Feature Table binary body; they cannot be embedded in the Feature Table JSON header.

The same is said for Point Clouds, and Batched 3D Models don't have any per-feature semantics.

Confirmed with @lilleyse that this is a conflict in the spec.

**Comment by lilleyse** [comment]
@Samulus this may a good 3D Tiles spec starter issue
