### ISSUE TITLE
Can I write the b3dm file for drone 3D model?

### ISSUE THREAD

**Issue by iamtekson** [CesiumGS/3d-tiles#397]
I want to add the features properties in the 3D model generated by the drone survey. Mean, I want to add the properties link building name, building height, building number, etc in this 3D model. I think I can do this with the help of b3dm. Is this possible?

**Comment by lilleyse** [comment]
@iamtekson yes that should be possible, b3dm can store application-specific metadata in its [batch table](https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/BatchTable).
