### ISSUE TITLE
obj to b3dm using the draco compression model

### ISSUE THREAD

**Issue by mylove10086** [CesiumGS/3d-tiles#404]
Hello, I have completed the conversion of obj to gltf using the draco compression model. But when I converted obj to a 3dtiles b3dm file and used the draco compression model, there was no success. When loading 3dtiles in cesium, the browser prompted ‘Unsupported draco mesh geometry type.’
But I didn't find the documentation about draco compressed 3dtiles on the cesium official website.
I have a question
How do I use draco to compress 3dtiles?
Can you provide a draco compressed b3dm file as a reference。

**Comment by lilleyse** [comment]
@mylove10086 - I'm going to close this for now, we can continue the discussion in https://github.com/CesiumGS/obj2gltf/issues/233
