### ISSUE TITLE
Bottom of polygons displayed when using Vector Data

### ISSUE THREAD

**Issue by Akbalder** [CesiumGS/3d-tiles#409]
I tried to generate a vctr tile containing polygons.
The tops of the bottom of the polygons are correclty displayed on the ground but the bottom of the polygons are also displayed under the ground!

Do you have any idea about what error I may have done?

**Comment by lilleyse** [comment]
@Akbalder are you using CesiumJS to display the vector tiles? This is probably a better question for the Cesium forum, make sure to include screenshots, sample data, and sample code, and we'll be happy to help.
