### ISSUE TITLE
Clarify Additive Refinement Behavior

### ISSUE THREAD

**Issue by gkjohnson** [CesiumGS/3d-tiles#416]
Hello!

I'm looking for some clarification on the intended behavior of the ADD refinement for tiles. From the spec it looks like the following tile structures would be valid:

**example 1**

```
root: REPLACE
└ t0: ADD
  └ t00: REPLACE
└ t1: ADD
  └ t10: REPLACE

```

What's the expected behavior here when **t00** meets the screen space error requirement but **t10** does not? If **t00** starts being rendered should **t10** be rendered even though it does not meet the requirements? Or should neither be rendered until both meet the screen space requirements? Or does REPLACE only replace the _immediate_ parent tiles' content meaning it would add to the root render?

Similarly for this case:

**example 2**

```
root: REPLACE
└ t0: ADD
└ t1: REPLACE
```

What's supposed to happen if t1 starts meeting the screen space error requirement? Is t0 supposed to stop being rendered as well as the root?

**example 3**

```
root: REPLACE
└ t0: ADD
  └ t00: ADD
    └ t000: ADD
```

Is this valid?

Thanks for the help! And thanks for all the effort put into opening up the 3d tiles spec.

**Comment by lilleyse** [comment]
I think there might be a slight mixup here. A tile's refinement determines how its children are rendered when it meets the screen space error requirement, not how its parent is rendered.

So in example 1 if **t100** meets the screen space error its content is replaced by its children (let's say **t000** and **t001**) and it doesn't affect any other tiles in the tree.

Likewise in example 2 **t1** would by replaced by its children, but **t0** and **root** would be rendered like usual.

**example 3** is valid as well. If **t0** met the screen space error and **t00** did not the rendered tiles would be **t0** and **t00**.

**Comment by gkjohnson** [comment]
Great thanks -- yes it seems I've misinterpreted the write up.

So just to be completely clear this means that if the root tile is set to refine type "ADD" then it will always be rendered and never be replaced by any other tiles, is that right? This also means there is no purpose to having a refine mode on the leaf tiles?

Thank you again!

**Comment by lilleyse** [comment]
> So just to be completely clear this means that if the root tile is set to refine type "ADD" then it will always be rendered and never be replaced by any other tiles, is that right? This also means there is no purpose to having a refine mode on the leaf tiles?

Yes, correct for both

**Comment by gkjohnson** [comment]
Great thank you!
