### ISSUE TITLE
How to make a lot of 3dmax files into one 3d-tiles? For example, there are 200 files with a total size of 6g.

### ISSUE THREAD

**Issue by The-End-Hero** [CesiumGS/3d-tiles#417]
How to make a lot of 3dmax files into one 3d-tiles? For example, there are 200 files with a total size of 6g.

**Comment by OmarShehata** [comment]
@The-End-Hero please post your question on the Cesium community forum! See: https://community.cesium.com/. 

Try exporting your models from 3DS Max as OBJ files and upload them to Cesium ion (https://cesium.com/ion/) or see the 3DS Max integration: https://cesium.com/docs/tutorials/integrating-with-3ds-max/.
