### ISSUE TITLE
How to "flyTo" to a picked feature of a 3DTileset 

### ISSUE THREAD

**Issue by lawrenceli19** [CesiumGS/3d-tiles#420]
Hi all, 

I've seen a cesium sandcastle sample which allows us to click on a feature and flyTo it. However, the requirement for this is to have the coordinate (Long,Lat) binds to the property of that feature. My B3DM doesnt have this property. Is there any alternative that allow me to achieve the flyTo? 

p/s: I've also seen flyToBoundingSphere. But I've no idea which boundingsphere in the pickedFeature object to get.

Please help. 

Thanks!

![image](https://user-images.githubusercontent.com/53752351/90214842-5f7a4f80-de2c-11ea-919c-23de09da6b22.png)

**Comment by OmarShehata** [comment]
Hey @lawrenceli19 , for implementation/usage questions like this, please post on the Cesium community forum: https://community.cesium.com.

CesiumJS doesn't have a built-in way to get the location of a given feature. There's some discussion on this here: 
https://community.cesium.com/t/3d-tileset-get-entity-based-on-attribute-in-order-to-fly-to-it/8328/2

Feel free to post a new topic on the forum to discuss your particular use case. For example, how did you generate your 3D Tileset? Can you regenerate it with lat/lon info on the features?
