### ISSUE TITLE
The effect of 3dtiles on FPS

### ISSUE THREAD

**Issue by mylove10086** [CesiumGS/3d-tiles#421]
When loading bim to 3dtile model, certain factors will affect the number of displayed frames. The following is the test done when displaying the same number of models:
1. The way to organize b3dm in tileset.json. When the octree organization model is used for hierarchical display, FPS will be significantly improved. If you simply organize multiple b3dm into tileset.json, FPS will be very low.
2. When debugging 3dtiles, the size of the Commands of Logging->statistics in viewer.extend(Cesium.viewerCesium3DTilesInspectorMixin); will affect FPS.

Question:
1. How can I optimize tileset?
2. What determines the Commands in statistics?
3. Does the organization of binary data in b3dm affect FPS?
4. How do i calculate geometricError?

**Comment by OmarShehata** [comment]
Hey @mylove10086 , the performance of your app will depend entirely on how the model is tiled and what client/viewer application you're using. Please ask your question on the Cesium community forum: https://community.cesium.com/. 

I would also encourage you to try uploading your model to Cesium ion (https://cesium.com/ion) to create an optimized 3D Tileset.
