### ISSUE TITLE
could b3dm tile format support glTFFormat(url or binary) like i3dm?

### ISSUE THREAD

**Issue by hanaimin** [CesiumGS/3d-tiles#425]
I 'd like to dynamicly append glb to tile header for some requirements. if download b3dm entirely every time, the header updating is a little slow because of glb too big.   
could b3dm tile format support glTFFormat(url or binary) like i3dm?

**Comment by xsxWang** [comment]
yes，of course

**Comment by ptrgags** [comment]
We now have an extension 3DTILES_content_gltf that can use glTF files directly as tile content (see https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf)

Though it would be helpful to determine the type of tile contents before downloading, see https://github.com/CesiumGS/3d-tiles/issues/388
