### ISSUE TITLE
Error calculation of empty tiles

### ISSUE THREAD

**Issue by liberostelios** [CesiumGS/3d-tiles#426]
Should empty tiles (ie. tiles without any content URL) be dealt in any special way, according to the standard?

There is one great [implementation](https://github.com/NASA-AMMOS/3DTilesRendererJS) of 3D tiles, which skips the calculation of the error for tiles that don't have a content URL. In NASA-AMMOS/3DTilesRendererJS#111 we were wondering if that's the behaviour that the standard dictates.

To give you a bit of a context, we are building a viewer based on 3DTilesRenderer and we basically just use layers of empty tiles to "hide" the ones with the actual content that are too far from the camera. For us, calculating the error and treating those empty tiles as normal is necessary, because the idea is that we only want to visualise content for leave tiles. But it's not clear if that's an intended behaviour based on the standard or whether we are stretching it out of its limits.

**Comment by gkjohnson** [comment]
I wanted to ping for an update on this -- the question boils down to "what's supposed to happen when there's an empty tile with children". Should the screen space error for the empty tile be calculated and traversal ended if the SSE threshold is not exceeded or should the SSE of empty node be skipped in favor of considering the child nodes. In the latter case an empty node would still be useful to improve frustum culling performance. It's not clear from the [geometric error section](https://github.com/CesiumGS/3d-tiles/tree/master/specification#geometric-error) what the proper behavior is. And the [section on grids](https://github.com/CesiumGS/3d-tiles/tree/master/specification#grids) mentions empty non leaf tiles being used for "hierarchical culling" but it's a bit ambiguous as to whether that means just frustum culling or also SSE culling.

@lilleyse you were very helpful before so hopefully you don't mind me pinging you!

**Comment by lilleyse** [comment]
Hey @gkjohnson 

The section I look to in the spec is this one:

> In a client implementation, geometric error is used with other screen space metrics—e.g., distance from the tile to the camera, screen size, and resolution— to calculate the SSE introduced if this tile is rendered and its children are not. If the introduced SSE exceeds the maximum allowed, then the tile is refined and its children are considered for rendering.

The intent is that traversal should stop if the SSE threshold is not exceeded for the tile, regardless or the tile's content. So geometric error should not be ignored for empty tiles. Perhaps "rendered" should be reworded as "selected"?

As you and @liberostelios pointed out, this enables finer grained culling via empty tiles. I could image a global dataset where  there's an empty tile around each city and the empty tiles should only refine once the camera is close enough.

This issue is pretty relevant because we recently encountered a tileset that didn't refine nicely unless geometric error was ignored for empty tiles, and while we opened a pull request with that change I don't think it's something we'll merge: https://github.com/CesiumGS/cesium/pull/9140

**Comment by gkjohnson** [comment]
Great thanks for the clarification @lilleyse. I think the word "rendered" is what threw me. Perhaps just adding a line of clarification that traversal should stop at tile regardless of whether or not has content would be helpful. In this case the SSE calculation is more about whether or not tree traversal should continue or not and less about rendering, right? At least that's how I thinking about it.

There's one case we're working with internally that specifies an empty root and a flat list of hundreds of children. We're effectively just using the tiles traversal for frustum culling and smart loading of tiles and not taking advantage of any of the hierarchical benefits. In this case however we always want to render the children tiles and never want to stop at the root. We could just specify that the root has a huge geometric error (`1e7`, for example) which would more or less guarantee that the children would always be traversed but I was wondering if you had any other suggestions for how to represent this type of tile structure?

Thanks again!

**Comment by lilleyse** [comment]
> We could just specify that the root has a huge geometric error (1e7, for example) which would more or less guarantee that the children would always be traversed but I was wondering if you had any other suggestions for how to represent this type of tile structure?

This sounds like the best approach for this type of tile structure

**Comment by liberostelios** [comment]
> There's one case we're working with internally that specifies an empty root and a flat list of hundreds of children. We're effectively just using the tiles traversal for frustum culling and smart loading of tiles and not taking advantage of any of the hierarchical benefits. In this case however we always want to render the children tiles and never want to stop at the root. We could just specify that the root has a huge geometric error (`1e7`, for example) which would more or less guarantee that the children would always be traversed but I was wondering if you had any other suggestions for how to represent this type of tile structure?

Regarding this example, I have a different question which is kind of related: assuming the aforementioned structure, all flat tiles will be loaded with respect to the camera's frustrum. But what about the error target? Currently, as soon as the traversal reaches the leaf nodes it will render everything. But should the renderer only pick to render those leaf tiles that have an SSE bellow the error target?

**Comment by lilleyse** [comment]
SSE controls when a tile refines to its children. The SSE of the child is not taken into account during this step.

To get the behavior you're describing the parent could have some empty children with their own geometric error and their own children with content.

**Comment by ptrgags** [comment]
Closing this issue since it seems resolved.
