### ISSUE TITLE
what's mean of "A tile's byteLength must be aligned to an 8-byte boundary."?

### ISSUE THREAD

**Issue by renjianqiang** [CesiumGS/3d-tiles#446]
As described in the title, i'm confused about the `byteLength` 8-byte aligned, i think this denote `byteLength` should be `8*n` bytes, but i found [batchedColors.b3dm](https://github.com/CesiumGS/cesium/blob/master/Apps/SampleData/Cesium3DTiles/Batched/BatchedColors/batchedColors.b3dm) has `13316` byte length, and `13316 % 8 = 4`.  Did I get it wrong? Or it just indicates that the `byteLength` itself should start at an 8-byte boundary?

And i also have some questions about the following description:

`
Binary properties must start at a byte offset that is a multiple of the size in bytes of the property's implicit component type. For example, a property with the implicit component type FLOAT has 4 bytes per element, and therefore must start at an offset that is a multiple of 4. Preceding binary properties must be padded with additional bytes, of any value, to satisfy this requirement.
`

Is the `offset` relative to the head of tile or the head of feature table binary body? I know it will be same because the binary body start and end on an 8-byte boundary, but i think it should be expressed more clearly to let others easier to understand if it could.

**Comment by lilleyse** [comment]
I think you uncovered a bug in `3d-tiles-samples-generator`. The b3dm byte lengths should be a multiple of 8. I opened an issue here: https://github.com/CesiumGS/3d-tiles-validator/issues/211

> Is the `offset` relative to the head of tile or the head of feature table binary body? I know it will be same because the binary body start and end on an 8-byte boundary, but i think it should be expressed more clearly to let others easier to understand if it could.

This is clarified in the spec further below:

>    * `byteOffset` specifies a zero-based offset relative to the start of the binary body. The value of `byteOffset` must be a multiple of the size in bytes of the property's implicit component type, e.g., the `"POSITION"` property has the component type `FLOAT` (4 bytes), so the value of `byteOffset` must be of a multiple of `4`.

Which is to say, the byte offset is relative to the head of the feature table binary body.

**Comment by renjianqiang** [comment]
Ok, thanks, now i got it!

Then i try to fix this bug by padding the binary glTF: [CesiumGS/3d-tiles-validator#212](https://github.com/CesiumGS/3d-tiles-validator/pull/212).

And i have a new question about [Batched3DModel#padding](https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/Batched3DModel#padding)
> The binary glTF must start and end on an 8-byte boundary so that glTF's byte-alignment guarantees are met. This can be done by padding the Feature Table or Batch Table if they are present.

I think there are some ambiguous in above description. The binary glTF must be [aligned to 4-byte boundary](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#chunks) instead of 8-byte boundary, so the binary glTF can start on an 8-byte boundary by padding the Feature Table or Batch Table,  but end on an 8-byte boundary only by padding  the binary glTF itself?

**Comment by onsummer** [comment]
Good question, learned a lot.
Confused about the meaning of 'padding', 'boundary', I think 'The b3dm byte lengths should be a multiple of 8' is easier to understand

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles-validator/pull/212
