### ISSUE TITLE
i3dm position and non uniform scale clarification

### ISSUE THREAD

**Issue by chenkianwee** [CesiumGS/3d-tiles#458]
I just like to clarify on the position and non-uniform scale features of a i3dm tile. I am instancing a gltf geometry as shown below (a 1x1x1m cuboild). The origin is in the centre of the bottom face of the cuboid as shown with the axis.
![image](https://user-images.githubusercontent.com/13062600/109876660-06df9800-7c40-11eb-88ba-ccb06facfaf9.png)

So in my i3dm file, I am instancing each cuboid with a position and a non uniform scale. This is an example file that I have generated, as shown in the figure below with 5 instances of varying heights.
![image](https://user-images.githubusercontent.com/13062600/109877774-6db18100-7c41-11eb-909e-ab308c0a7050.png)

So here are the questions that I need some clarification, and I can't seem to find answers in the specifications (I apologise if I have missed it, you can point me to the right section of the documentation):

1). From the result, it looks like the position specified in the feature table corresponds to the centre of the cuboid and not the origin of the gltf model? So the mapping of the gltf to the position is dynamic? It will always be the centre point of the geometries in the gltf model and not the origin of the gltf model? 

2.) In the non uniform scale, the y-component correspond to up (z-axis)? I thought in 3d tiles up is always z-axis.

I have attached the i3dm example file here if it helps. Thanks. 
[tree_tiles.zip](https://github.com/CesiumGS/3d-tiles/files/6079477/tree_tiles.zip)

**Comment by lilleyse** [comment]
1. It's possible this is a CesiumJS bug. I would expect the instance position to apply to the origin of the model. Could you open an issue there if you're still seeing this issue?
2. The z-component of the scale applies to the y-axis of the glTF. This mismatch is a side effect of glTF having a y-up coordinate system. CC #504
