### ISSUE TITLE
Adding explanation for URIs in i3dm files to specification

### ISSUE THREAD

**Issue by dzungpng** [CesiumGS/3d-tiles#461]
Currently in the spec, there is a [section ](https://github.com/CesiumGS/3d-tiles/tree/master/specification#uris) to explain URIs in tileset.json. However, there is no such section for URIs in i3dm files. Although this can be figured out by looking at [this code snippet](https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Instanced3DModel3DTileContent.js#L315) in `Instanced3DModel3DTileContent.js`, it would be helpful to document it in the spec as well.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles/pull/568
