### ISSUE TITLE
Wrong type for component type in binary body reference of Feature Table

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles#467]
The [Feature Table `binaryBodyReference.componentType.type`](https://github.com/CesiumGS/3d-tiles/blob/f27d3aaa08ca32afc05281d115c91c3da0dfb264/specification/schema/featureTable.schema.json#L18) is declared to be `"number"`. I think this should be `"string"`. 

(The type `number` does not match the types in the `enum`, and in [the Batch Table, the type of the `componentType` is declared to be a `string`](https://github.com/CesiumGS/3d-tiles/blob/f27d3aaa08ca32afc05281d115c91c3da0dfb264/specification/schema/batchTable.schema.json#L29))

**Comment by lilleyse** [comment]
@javagl good catch, can you open a PR?

**Comment by javagl** [comment]
@lilleyse I wasn't sure how "important" that was considered to be, and ... spec changes are always difficult, considering possible implications for ratifications or whatnot,. But ... I opened a PR, so that someone who knows the implications can merge it or leave it.

**Comment by lilleyse** [comment]
Thanks I merged the PR. Generally we're ok with merging "bug fixes" like that.
