### ISSUE TITLE
What's the progress for the extensions that recently commited?

### ISSUE THREAD

**Issue by onsummer** [CesiumGS/3d-tiles#471]
I noticed that the official has submitted several interesting 3dtiles extensions on other branches in recent months, and also noticed the updated code in the latest `Cesium.js`, but I don’t know when these interesting content will be made public?

Sorry for I don't know where to ask this and I open a issue here.

**Comment by ptrgags** [comment]
Hi @onsummer, good question. The extensions on the `3d-tiles-next` branch are draft extensions to 3D Tiles that we've been prototyping in CesiumJS.

For an overview of the 3D Tiles Next extensions, see here: https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/3D_TILES_NEXT.md

Some extensions have already been implemented and are available in the `master` branch of CesiumJS, see this CesiumJS issue: https://github.com/CesiumGS/cesium/issues/9520

Sometime In the coming months, we plan to add a big-picture roadmap for 3D Tiles on our [blog](https://cesium.com/blog/), though not sure when exactly yet.

If you have any other questions about CesiumJS or 3D Tiles, please ask them on our forum: https://community.cesium.com/

**Comment by onsummer** [comment]
@ptrgags Thank you for your reply!
