### ISSUE TITLE
Non-relative URIs in Tilesets

### ISSUE THREAD

**Issue by fkhaller** [CesiumGS/3d-tiles#472]
I am not sure if this is allowed but I am trying to use a uri in my tileset.json that is non-relative and it doesn't seem to work :
`"content": {
      "uri": "http://localhost/parent.b3dm",
      "boundingVolume": {
        ...
      }
      }`
Is this something that should work or must the file be collocated with the tileset.json?

**Comment by ptrgags** [comment]
@fkhaller To answer your question about whether this is allowed, here's an answer from the spec. In the [URIs section](https://github.com/CesiumGS/3d-tiles/tree/master/specification#uris) of the specification it says that:

>Client implementations are required to support relative external references and embedded resources. Optionally, client implementations may support other schemes (such as http://). All URIs must be valid and resolvable.

In other words, absolute `http://` URLs are allowed, but support may vary depending on the implementation.

Where are you using this tileset? CesiumJS or Cesium for Unreal? CesiumJS supports absolute URIs. I'm not familiar enough with Cesium for Unreal to give an answer about that implementation. Either way, the solution is likely to double check your URI:
    
* Is the B3DM file served on `localhost` port 80? That's what the URI you mention implies
* (CesiumJS specific) Check the console for errors, In the browser, same-origin security policies can easily block cross-origin requests. My guess is it could be one of these:
    * Mixing `http` and `https` in the same page (they need to both use the same protocol)
    * Same host but different ports. if the tileset is on say `localhost:8080` but the B3DM is on `localhost:80`, the browser views these as different origins. This can be addressed by enabling CORS on the server that hosts the tileset and other files.
    
If you need further support for CesiumJS or Cesium for Unreal, please use the forum: https://community.cesium.com/. This repository's issue tracker is focused on questions about the 3D Tiles specification only.

**Comment by ptrgags** [comment]
Since there's nothing actionable on our end, I'm closing this issue for now.
