### ISSUE TITLE
Cant select generated b3dm from pg2b3dm in Cesium

### ISSUE THREAD

**Issue by carnegiea** [CesiumGS/3d-tiles#474]
Hi,

I have tried using pg2b3dm to generate 3dtiles with tileset.json.
However after uploading to Cesium, it cant be selected. Meaning the mouse click on the model has not pop out.
I am not sure what problem, is it due to geometricError parameter?

The batchTable is valid as I could use b3dm-tile-cs to read it out.
If someone could have faced the same issue and can enlighten a bit? 
Greatly appreciated. 

I can share the b3dm datasets if required.

Thanks
Carn

**Comment by lilleyse** [comment]
Hi @carnegiea, can you create a post on the [cesium community forum](https://community.cesium.com/) and share your dataset there? You should be able to get a better answer there, we use github for issue tracking and feature requests only. Thanks!
