### ISSUE TITLE
I have a 40G 3DTileset  . It is very busy when loading. How can I load the process?

### ISSUE THREAD

**Issue by iiixxxiii** [CesiumGS/3d-tiles#481]
I have a 40g 3DTileset  . It is very busy when loading. How can I load the process?

**Comment by ptrgags** [comment]
Hi @iiixxxiii, could you provide more information on this tileset?

Is this a tileset that was uploaded to Cesium ion? If so, you might want to search through the [Cesium Community Forum](https://community.cesium.com/) to see if anyone has asked a similar question.

If this is a tileset that you created yourself using the 3D Tiles specification? If so, could you describe the tileset in more detail?
* Are the contents `B3DM`, `I3DM`, `PNTS`, or `CMPT` tiles? 
* How is the tileset divided into tiles? Do you have a few large tiles or many small tiles? If your tiles are large, it might be a good idea to break them up into smaller tiles so each tile streams in faster.

Also, what are you using to load the tileset? CesiumJS or Cesium for Unreal? Both have sections on the forum for questions (please see the link above).

**Comment by iiixxxiii** [comment]
@ptrgags  contents is b3dm , 4938 directories  , CesiumJS load

**Comment by ptrgags** [comment]
@iiixxxiii, another thing to check is how the tileset is subdivided. [this blog post](https://cesium.com/blog/2017/03/30/spatial-subdivision/) includes some suggestions for optimization.

If you need further support, please use the forum (see the link in my previous comment)
