### ISSUE TITLE
Any way to convert 3D tile set to Nexus nxs file ?

### ISSUE THREAD

**Issue by cyrilpreiss** [CesiumGS/3d-tiles#482]
Is there any way to convert 3D tileset to Nexus nxs file ?

**Comment by ptrgags** [comment]
@cyrilpreiss Could you please ask this question on the [Cesium Community forum](https://community.cesium.com/)? Thanks! We use the forum for support questions like this. the `3d-tiles` repo is for discussion about 3D Tiles specification only.
