### ISSUE TITLE
Clarify how query parameters are handled when requesting external tilesets

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/3d-tiles#484]
Right now, the specification does not explain how query parameters are handled 

Talking with @lilleyse, we think that it should work like this:

* Query parameters for the tileset are inherited by all contents
* If a tile contains an external tileset, the child tileset uses query parameters from both the parent and child. In the case of name conflicts, the child's parameters take precedence as they are more specific.

In JavaScript ES6 syntax, this could be expressed like this:

```javascript
const queryParameters = {
  ...parentTileset.queryParameters,
  // if there are name collisions, the child's values are used.
  ...childTileset.queryParameters
};
```

If we add this to the specification, another thing to consider is does this warrant a version bump and how does this affect standardization.

**Comment by lilleyse** [comment]
I confirmed that CesiumJS is doing what you described above, though I haven't checked how it resolves name collisions. Query parameters are passed along to contents, external resources (textures, etc), and external tilesets (recursively).

<img width="1422" alt="Screen Shot 2021-09-23 at 3 10 35 PM" src="https://user-images.githubusercontent.com/915398/134568995-a879814f-063f-4fa9-8ad0-d6f7cf388ff1.png">

Note in the screenshot above that tileset2.json has `tilesetVersion: 1.2.3` which is automatically added as a query parameter for caching purposes. Though this behavior isn't explicitly defined in [`asset.schema.json`](https://github.com/CesiumGS/3d-tiles/blob/main/specification/schema/asset.schema.json).

**Comment by lilleyse** [comment]
> though I haven't checked how it resolves name collisions

The default behavior of `Resource.getDerivedResource` (which the 3D Tiles code uses heavily) is that derived parameters will replace those of the current resource.

![Screen Shot 2021-09-23 at 3 23 31 PM](https://user-images.githubusercontent.com/915398/134570863-9731e4cb-9689-41d2-8d5a-56f6a0450cbc.png)

https://cesium.com/learn/cesiumjs/ref-doc/Resource.html#getDerivedResource

**Comment by donmccurdy** [comment]
Within the glTF specification we've avoided requiring inheritance of query parameters (override vs. merge vs. no inheritance). Implementations may choose to infer query parameters on textures or `.bin` files based on the root `.gltf` file URL, for use cases like `?token=<TOKEN>`, but that should generally be informed by some context known to the application: which types of resources do parameters affect, which parameters are inherited and which are not, and whether the tiles are accessed by HTTP request or reading from disk.

I think the same complexities apply here, and that URIs should be interpreted "as written" unless an application has some context outside the scope of the 3D Tiles specification.
