### ISSUE TITLE
Clarify upsampling requirements in 3DTILES_implicit_tiling

### ISSUE THREAD

**Issue by kring** [CesiumGS/3d-tiles#489]
In Cesium World Terrain, it doesn't really make any sense for just 1, 2, or 3 child tiles to be available for rendering. Either the tile is a leaf and has 0 children available, or, if we refine this tile, we're going to need to be able to render all 4 of its children. If we refine a parent tile but only have three children, there would be a hole where the fourth child is meant to be.

However, it's actually fairly common in Cesium World Terrain to have a tile with only 1, 2, or 3 tiles marked as available. When this happens, the client is expected to _subdivide the parent tile to create the missing children_, a process that is called "upsampling" in CesiumJS and cesium-native. This is a small optimization, reducing the number of pre-generated tiles that need to be stored and transmitted.

In the more general case of 3DTILES_implicit_tiling, though, a missing child tile might be common and normal and not indicate any need for upsampling. For example, if the tileset is buildings, there may simply not be any buildings in the area of a child tile.

So, some questions:
1. Should we enshrine "no need to upsample" in the 3DTILES_implicit_tiling spec? This will make client implementation easier and more performant.
2. Should there be a way to indicate that upsampling _should_ happen? This would make it easier to convert Cesium World Terrain and similiar to 3DTILES_implicit_tiling (and may help out other tilers in a similar boat), but at the cost of client complexity.

**Comment by ptrgags** [comment]
I wonder if the distinction should depend on the type of refinement? e.g. `REPLACE` refinement would require all four children to be present (e.g. terrain) while `ADD` refinement doesn't have this restriction (e.g. for buildings)

**Comment by kring** [comment]
I don't think so @ptrgags, because buildings could be REPLACE as well. It will never _hurt_ to do the upsampling, though, it's just (potentially unnecessary) complexity.

As an aside, I kind of think we should deprecate ADD refinement. It has problems:
1. Precision. Additive refinement means geometry from large tiles is sometimes viewed up close, which is a recipe for poor precision.
2. Even worse precision when the position attribute is quantized or otherwise compressed.
3. It's very difficult to sensibly drape raster overlays on additive-refined tileset.

Of course, we could turn an ADD tileset into a REPLACE one at runtime, and very well may end up doing that in Cesium for Unreal, but I'm not sure the value of ADD refinement actually outweighs the costs.

**Comment by kring** [comment]
> Clients should be able to trust the availability info, and know that the upper right child is not available, because ... there is nothing.

Yes, I think I agree. Clients should never be required to upsample, and the spec should say so. Or perhaps no one outside of Cesium would even think of doing that anyway, so it doesn't really need to be mentioned. That will make it slightly more work to convert Cesium World Terrain to 3D Tiles with 3DTILES_implicit_tiling, but that's ok.

**Comment by lilleyse** [comment]
I say we close this for now - if `3DTILES_implicit_tiling` marks content as unavailable then that volume of space should be considered empty. It's the tiler's responsibility to fill that space with upsampled content if needed.

`cesium-native` will just need backwards compatibility for quantized-mesh.

**Comment by IanLilleyT** [comment]
It would be useful to make content availability even stricter:
- child content should either be all available or all unavailable
- child content cannot have unavailable parent content  

This means:
- No more runtime upsampling (see above comments)
- Leaf tiles must have content
- Easier to determine if something is a leaf tile. Right now you have to check descendent content availability which could mean fetching entire subtrees. This could be avoided by introducing a _child subtree content availability_ that has a recursive definition. But that feels like too much work.
- Geometry cannot not disappear and reappear as the camera zooms in. If this is actually desired behavior it should be handled on the tiler level and write zero triangles / points / etc for the content. (Is this allowed in glTF?)

I probably have several blindspots. Is anything made worse or impossible with these rules?

**Comment by javagl** [comment]
> I probably have several blindspots.

Me too. But a few short comments:

> child content cannot have unavailable parent content 
> [...]
> If missing geometry is actually desired it should be handled at the tiler level by writing zero triangles / points / etc for the content. (Is this allowed in glTF?)

This is allowed. `{ asset { version: 2.0 } }` is a complete, valid glTF 2.0 asset. But ... something might have to be done to prevent the client from sending out hundreds or thousands of requests for ... essentially empty files. 

> Leaf tiles must have content

This sounds sensible for me (I always wondered what could be the purpose of leaf tiles without content, but they considered that they might carry some other data). 

But ... when all leaf tiles must have content, and this implies that their parents must have content, then ... I think that some of the data structures ... "collapse": Right now, they store availability information for tiles and content, for each node in a tree. With these additional constraints, they'd basically just describe ~"the set of available leaves", and then there might be an easier and more compact representation of that. (I think you once mentioned the option of having something like a `deepestAvailableLevel` and `depthUpToWhichTheTreeIsComplete` or so...?)

(I'll probably have to re-read this and think more thoroughly about the implications on the spec - and even then, I could hardly foresee the implications for the _implementation_, so I'm curious what others think...)

**Comment by IanLilleyT** [comment]
I might need to change the second rule from
```
child content cannot have unavailable parent content
```
to
```
child content cannot have unavailable parent content if it has an ancestor with available content
```

This would mean content availability is still needed after all - to handle cases like content decimation being unacceptable and only leaf tiles being allowed to render. Maybe useful for CAD models. You still get the benefit of occluding tiles that are offscreen but you'd have to crank down your geometric error to 0.

A more typical example is a double headed quadtree that has a root tile with no content

**Comment by javagl** [comment]
A related issue, about the role of "empty tiles" that are used for culling (but not refinement): https://github.com/CesiumGS/3d-tiles/issues/609
