### ISSUE TITLE
Inverse transformation of ENU rotation

### ISSUE THREAD

**Issue by skymapdev** [CesiumGS/3d-tiles#494]
I have been working on a way to align the b3dm files to local coordinates. As I'm not well versed in the operations of projection transformation, neither the required steps nor the mathematics behind it, which makes this quite a rough task. 
Currently the geometry follows ENU (as I understand it), and should you load it for example in a framework like ThreeJs, the geometry does not align with for example a tiled point cloud of the same area, if both are loaded 'as is'.

While the point cloud is presented using the the local up, the 3d model (b3dm) is rotated according to its geographical position. 

There is probably a straight forward way to calculate the rotation matrix for aligning the geometry to local space, but without experience or indepth knowledge on how to do this, gathering and extracting this information has been difficult.

I suggest either put a section describing on how to do this in the format specification, or maybe adding an 'inverseENU' rotation matrix to the b3dm feature table. The first allows users to find the information, and get a grasp of the case and reason for the rotation, and how to calculate the correct matrix to reverse the rotation. The other (with description added to the format specification) allows to get running quicker. 

As I said, I do not have an in depth understanding of projections and transformations, but after a couple of days searching I'm not much closer to reverse the rotation of the model.

**Comment by lilleyse** [comment]
This depends on the particular b3dm and the tiling pipeline that generated it.

Sometimes the b3dm will appear rotated if its vertices are defined in global coordinates. But the b3dm can also be defined in local coordinates and the tile transform can position it on the globe. The full chain of transformations is defined here and there's some flexibility to the approach taken: https://github.com/CesiumGS/3d-tiles/tree/main/specification#transforms

To transform global coordinates back to local ENU coordinates you can use the inverse of the [eastNorthUpToFixedFrame](https://cesium.com/learn/cesiumjs/ref-doc/Transforms.html#.eastNorthUpToFixedFrame) matrix. It takes a center point in global cartesian coordinates. The exact details may depend on your data.
