### ISSUE TITLE
Extensions properties should point to extensions schema

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles#495]
The `extensions` property in the schema files of extensions is currently defined as 

    "extensions": {},

(for example, [here](https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/extensions/3DTILES_content_gltf/schema/tileset.3DTILES_content_gltf.schema.json#L23), but it appears to be done consistently like that for the extensions).

In the core schema, the extensions are pointing to the [`extension.schema.json`](https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/specification/schema/extension.schema.json), via

        "extensions" : {
            "$ref": "extension.schema.json"
        },

(for example, [here](https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/specification/schema/content.schema.json#L16), but it appears to be done consistently like that for the core)

---

I *think* that the extensions should also point to the `extensions.schema.json` (despite the difficulty that *might* arise from "nested extensions" - they are currently *required*, e.g for combining `3DTILES_multiple_contents` and `3DTILES_metadata`).

---

The same is currently true for the [glTF `gltf.EXT_mesh_features.schema.json`](https://github.com/CesiumGS/glTF/blob/8e4fde4d06590f365d1ca9a729f80db33f6472e0/extensions/2.0/Vendor/EXT_mesh_features/schema/gltf.EXT_mesh_features.schema.json#L32), which should similarly point  to the [glTF `extension.schema.json`](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/extension.schema.json).

**Comment by lilleyse** [comment]
@javagl good timing - I already did this in https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next-json-schema-2020-12 and plan to open a PR soon.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles/pull/497

**Comment by javagl** [comment]
I think they are still explicitly listed, e.g. https://github.com/CesiumGS/3d-tiles/blob/main/specification/schema/boundingVolume.schema.json#L40 - I hope it's OK to reopen

**Comment by lilleyse** [comment]
3D Tiles schemas are mostly followed what glTF is doing. If glTF changes we should change here as well, but until then maybe not worry about it?

**Comment by javagl** [comment]
Based on a [recent comment](https://github.com/KhronosGroup/glTF/issues/2062#issuecomment-934201170), *... we can stop putting empty name, extras, and extensions everywhere"*, but the next comment indicated that this would likely happen after the existing glTF extension schemas have been updated to the latest JSON Schema version

We could do that change here and remove the `extensions` and `extras`, because everything here already uses the latest schema. But it may make sense to wait until this is done for glTF, because... *if* there are any issues or caveats with removing these properties, then they will be found and solved there.

I think it's OK to leave this issue open as a reminder, but again: If it should be closed because there is no immediate action, then that's also fine for me.
