### ISSUE TITLE
Consider avoiding ambiguities for property names in extensions

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles#496]
There are some cases where extensions define a new property that has *the same name* as a property of the extended object. For example, [`tile.3DTILES_multiple_contents.schema.json`](https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/extensions/3DTILES_multiple_contents/schema/tile.3DTILES_multiple_contents.schema.json#L7) defines a property that is called `content`, and that is an *array*, and [`tile.schema.json`](https://github.com/CesiumGS/3d-tiles/blob/main/specification/schema/tile.schema.json#L36) defines a property that is called `content`, but this is a single object.

In order to avoid ambiguities, one should *consider* to avoid overloading names like that.

**Comment by donmccurdy** [comment]
Both `content` and `contents` seem equally fine for an array in my opinion, the term "content" is more [uncountable](https://dictionary.cambridge.org/us/grammar/british-grammar/content-or-contents) than singular. But agree that consistency in usage and type is important.

**Comment by lilleyse** [comment]
It might make sense to rename it to `contents` in the extension now.

To support multiple contents in 3D Tiles 1.1 without introducing a breaking change we added a `contents` property: https://github.com/CesiumGS/3d-tiles/pull/634#discussion_r812108700. 3D Tiles 1.1 and `3DTILES_multiple_contents` should have consistent naming.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles/pull/649
