### ISSUE TITLE
Add a property to specify the CRS of the tileset

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#504]
A long running source of confusion is that 3D Tiles and glTF have different coordinate systems. 3D Tiles uses a generic right-handed cartesian coordinate system where the z-axis can mean different things depending on whether the tileset is in a global or local coordinate system, while glTF is strictly y-up.

This breaks down quickly once you're working with geospatial data that doesn't have an up-axis. This tile here is glTF but it doesn't _really_ have an up axis like a regular game asset would.

<img src="https://user-images.githubusercontent.com/915398/137203709-e9d3c1cd-b52b-481b-a162-d9cae2504ea9.png" width="400" />

[<sub>Sandcastle</sub>](https://sandcastle.cesium.com/#c=vVNhS8MwEP0roZ8mjHSiIMw61FlEmJvo9Iv1Q9aeWzBLSnLdVsX/7nXJpsx91VJo3rv37u6VdiEsW0hYgmVnTMOS9cHJas6f1lwri/I17huNQmqwWXRwmulMew93OWjgU2UmwAsocTYGhxdTkjocg7V0oL5oK/AummZFIStH7GHHX7xz6ivUC3f36AuLdBL6qBWYW4Eznt493AxGw5M269B9sG2+IndYjZpJlOC4KIrWR6YZK42qFYXosjVsCEcSo12XPXuGhSXaG7h/FZ8hDA/al/BcygJnXXYcoLD5uC5pZuhy4TEfjoZpkMwFTZRCbTV9o4zl9+lVU/8k1ed3wvp/ElKybcg/S3h9n6bDPRnf/y3jNuafZbwcPKa7EUO0FYIuNp+1Jz240a6EHI29lSupG1PUjhKHtYLeJtK5nJfGIqusanEeI8xLRRu4eFLlb4A8d64xNtIk/mlNCrlgsjjb82uzXAnnqPJaKfUg3yGLeklM+l9WZeit6eloAVaJupHNDnsDT3LOk5jgficaoybC7nT+Ag)

3D Tiles 1.0 is very strict about honoring the glTF up-axis. The spec requires that a y-up to z-up transform is applied on glTF assets, which means that if you have data that is inherently EPSG:4978 you need to include the reverse transform z-up to y-up in the glTF, either as a node or baked into the positions themselves. The [transforms](https://github.com/CesiumGS/3d-tiles/blob/main/specification/README.md#transforms) section goes into the full details. This behavior has led to much confusion over the years and doesn't feel right.

Now with 3D Tiles Next we have a chance to change this behavior. I think the glTF up axis should be ignored since it doesn't make sense in a geospatial context. Instead the glTF should be considered to be in the tileset's coordinate system. This way no additional transforms need to be applied at runtime or in the glTF.

In order to do this without breaking changes with 1.0 we can define this behavior in [`3DTILES_content_gltf`](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/extensions/3DTILES_content_gltf). Basically if you have a b3dm you follow the previous rules, but if you have a glTF/glb you follow the new rules (less rules). I would expect the new behavior to be the default in 3D Tiles 2.0.

CC @ptrgags @sanjeetsuhag @donmccurdy @javagl @IanLilleyT

**Comment by lilleyse** [comment]
Just to clear up something, EPSG:4978 is the global cartesian coordinate system (pictured above) not lat/long/height (EPSG:4979). Latitude/longitude/height only shows up in the spec for defining `region` bounding volumes but that doesn't impact data storage, so vertex attributes would still be cartesian and meters.

The main point is that a lot of geospatial data doesn't even have the concept of an up axis or forward axis because it's captured or processed as EPSG:4978 and lives in this global context.

But if you have data in a local coordinate system, like a glTF outputted from photogrammetry software that spans a small-enough geographic area and is y-up, the user workflow shouldn't change, but the glTF to 3D Tiles converter would create glTF tiles that are now z-up in the local coordinate system... so admittedly that breaks the confidence that the tiled glTF is y-up but the user doesn't have to do anything different with their source glTF which can stay y-up.

But I think the more common case is that a user wants to convert their glTF to 3D Tiles and geolocate the data, in which case the glTF tiles would be EPSG:4978 and we would run into the same problems as before and it's just easier to say "the glTF uses the same coordinate system as the tileset" than try to impose up axis conversions that don't really make sense in the global context.

**Comment by javagl** [comment]
I think this may be related to an ancient issue: https://github.com/CesiumGS/3d-tiles/issues/286

**Comment by lilleyse** [comment]
Draft of what this might look like for 3D Tiles

```json
{
  "asset": {
    "version": "1.0"
  },
  "extensions": {
    "3DTILES_coordinate_reference_system": {
      "crs": "EPSG:4978"
    }
  }
}
```

CRS would be either [`EPSG:4978` or `local`] where `EPSG:4978` is the geocentric coordinate system based on the WGS84 ellipsoid and `local` is a local right-handed Z-up cartesian coordinate system (described [here](https://github.com/CesiumGS/3d-tiles/tree/main/specification#coordinate-reference-system-crs)).

This extension would redefine the transformation behavior in 3D Tiles, which is much easier to do if we ignore b3dm, i3dm, pnts, cmpt and omit the glTF y-up to z-up conversion.

Essentially it is a simple scene graph where T0, T1, etc are tile transforms and N0, N1, etc are glTF node transforms. After transforms are applied a vertex is expected to be in the tileset's coordinate system.

![image](https://user-images.githubusercontent.com/915398/142308429-7dfb1a66-ad0d-4242-a78d-ea2936d4ab1d.png)

**Comment by jailln** [comment]
Nice thanks :) 
I propose that we allow any EPSG code for the `crs` attribute though (instead than limiting it to `EPSG:4978`). What's your opinion on this ?

**Comment by lilleyse** [comment]
I do see the benefit of bringing 3D Tiles spatial subdivision to other coordinate reference systems, but I don't think it would fit with 3D Tiles goal of being runtime efficient. Clients would need a projection library and access to grid shift files in order to transform positions for the GPU. Plus there's just a nice simplicity that 3D Tiles only supports cartesian coordinate systems.

**Comment by donmccurdy** [comment]
Perhaps a distinction worth making between "the extension allows >1 CRS" and "clients must implement >1 CRS". I would certainly not expect most clients to implement support for more than a couple EPSG codes. Whether this means others should be prohibited at the spec level, I'm not sure.

If we do think it's preferable to allow only EPSG:4978, perhaps we rename the extension from `3DTILES_coordinate_reference_system` to `3DTILES_epsg_4978` or similar? Then at least there is a cleaner path to allowing more in the future than `3DTILES_coordinate_reference_system_v2,3,4,...`.

**Comment by lilleyse** [comment]
For comparison I3S supports two global CRS - EPSG:4326 and EPSG:4490 - and any number of local CRS

[I3S Coordinate Reference Sytstems](https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#CRS)

> All I3S profiles support writing 3D content in two modes: global and local. In global mode, only the geographic CRS WGS84, as identified by its EPSG code 4326, and GCS China Geodetic Coordinate System 2000, as identified by its EPSG code 4490, are supported for both index and vertex positions. It is represented using longitude, latitude and elevation. In local mode, all other geodetic CRS, including projected coordinate systems, are allowed.

**Comment by lilleyse** [comment]
Going along with the idea of `3DTILES_epsg_4978`, sometimes it's important to know the `realization` and `epoch` of the WGS84 model. These could be included in the schema as optional properties.

EPSG Code|Realization|Year published|Epoch|Notes|Accuracy compared to ITRF
--|--|--|--|--|--
4326|WGS84|1987||Identical to NAD83|1-2 meters
4326|WGS84 (G730)|1994|1994.0|Based on ITRF91|10 cm/component rms
4326|WGS84 (G873)|1997|1997.0|Based on ITRF94|5 cm/component rms
4326|WGS84 (G1150)|2002|2001.0|Based on ITRF2000|1cm/component rms
4326|WGS84 (G1674)|2012|2005.0|Based on ITRF2008|<1cm/component rms
4326|WGS84 (G1762)|2013|2005.0|Based on ITRF2008|<1cm/component rms

**Comment by jailln** [comment]
I agree with @donmccurdy that allowing it in the extension doesn't mean that every client should support this extension neither that it should support it fully. Allowing more than one CRS however gives more flexibility to tilesets creators and clients.

In addition, 3D Tiles in other CRS than 4978 are already created / displayed but their CRS is not explicitly stored in the tileset. For instance:
-  [py3dtiles](https://gitlab.com/Oslandia/py3dtiles/-/tree/master/) support creating 3D Tiles in many CRS (with --srs_in and --srs_out options)
- the 3D Tiles ecosystem for mapbox/maplibre ([mapbox-3dtiles](https://github.com/Geodan/mapbox-3dtiles) and [pg2b3dm](https://github.com/Geodan/pg2b3dm) work in EPSG:3857 since it was the only CRS supported by mapbox until very recently
- [itowns](https://github.com/itowns/itowns) can read and display 3D tiles in many CRS
- RhinoCity software also allows to produce 3D Tiles in many CRS
- ...

One might ask what a 3D dataset into a 2D projected coordinate system means, and if we should provide this possibility in 3D Tiles... Nevertheless it is currently quite used and generally it just means geolocalizing the 3D objects in this 2D coordinate system for using it in clients that don't support other CRS or for combination with datasets in local projections that cannot or should not be reprojected.

**Comment by jerstlouis** [comment]
It might be a good idea to conside the new [TileSet metadata](https://docs.opengeospatial.org/DRAFTS/17-083r3.html#tile-set-metadata) specification, which is intended to also support 3D use cases.
Perhaps its schema could be integrated here, and we could extend it to handle 3D data types?

**Comment by donmccurdy** [comment]
^This got me thinking about the extension vs. metadata distinction, and I wrote up some thoughts in https://github.com/CesiumGS/3d-tiles/issues/600. In the end I didn't come up with a preference on the suggestion though. 😅

**Comment by lilleyse** [comment]
https://github.com/CesiumGS/3d-tiles/pull/633 added the ability to provide the geocentric CRS and coordinate epoch.

Some of the other discussion in this issue related to up-axis conventions has not been addressed yet, but https://github.com/CesiumGS/3d-tiles/issues/587 seems to be a promising direction.
