### ISSUE TITLE
Why doesnt show model when set trasform property as node matrix in b3dm?

### ISSUE THREAD

**Issue by learnerandtrainer** [CesiumGS/3d-tiles#505]
Hi,
I have a model and it can be showing on cessium when set trasnform property in tileset.json file. But when I set this transform parameter in the b3dm as node matrix. it doesnt work . Why is it happen? does not the node matrix equals to trasnform?
Here my models 
work
[15_work.zip](https://github.com/CesiumGS/3d-tiles/files/7346179/15_work.zip)

doesnt work
[15_doesntwork.zip](https://github.com/CesiumGS/3d-tiles/files/7346190/15_doesntwork.zip)

**Comment by lilleyse** [comment]
See #504 - this is likely due to the mismatch of 3D Tiles coordinate system and glTF coordinate system.

You may need to multiple your node matrix by a z-up-to-y-up transform.
