### ISSUE TITLE
Decouple spatial subdivision and metadata from 3D Tiles

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#519]
This is a roadmap item for an idea we have discussed but I don't think we have written down.

3D Tiles is basically:
* Spatial subdivision
* glTF
* Metadata
* Declarative styling

3D Tiles Next is basically
* Explicit and **implicit** spatial subdivision
* Cleaner integration with **glTF**
* More robust and efficient **metadata**

As we look to metaverse use cases such as
* Spatial subdivision for AR to overlay the digital world onto the physical world
* Metadata (+ behaviors) to allow interoperability of assets among metaverses, e.g., export asset from Roblox and import to Fortnite

3D Tiles has the opportunity to broadly solve spatial subdivision and metadata interoperability, e.g.,
1. Spatial subdivision with USD as the tile payloads
2. Spatial subdivision within a glTF file with glTF nodes as the payload
3. glTF asset with just the metadata extensions to describe a car that can be imported into multiple metaverses
4. USD asset using a metadata semantic extension and the core metadata type system, but a USD-appropriate encoding

I believe some of these use cases are already possible (**3** for sure) and that others are just about there so this could be more about positioning, documenting, and inspiring than any major changes.  Just asking that we have the decoupling thought through and the big metaverse ecosystem interoperability vision in mind.

CC @donmccurdy @lilleyse @ptrgags

**Comment by donmccurdy** [comment]
Thinking about (4) and (5) — at least as a thought exercise, it's helpful to compare the [Semantic Reference](https://github.com/CesiumGS/3d-tiles/tree/main/specification/Metadata/Semantics) to the [XMP Dublin Core Namespace](https://www.adobe.io/xmp/docs/XMPNamespaces/dc/), or perhaps other namespaces. Can we cleanly map XMP namespaces in general to 3D Metadata semantics and encodings? Some of XMP's higher-level types, like Language Alternatives, are not so trivial for encoding. Below is a `dc:title` property value, analogous to `NAME` in 3D Metadata, except that it includes translations:

```xml
<xmp:Title>
    <rdf:Alt>
        <rdf:li xml:lang="x-default">XMP - Extensible Metadata Platform</rdf:li>
        <rdf:li xml:lang="en-us">XMP - Extensible Metadata Platform</rdf:li>
        <rdf:li xml:lang="fr-fr">XMP - Une Platforme Extensible pour les Métadonnées</rdf:li>
        <rdf:li xml:lang="it-it">XMP - Piattaforma Estendibile di Metadata</rdf:li>
    </rdf:Alt>
</xmp:Title>
```

I'm not sure what the JSON-LD encoding of that would be, but here's a rough guess:

```jsonc
{
    "dc:title": [
        {"lang": "x-default", "value": "XMP - Extensible Metadata Platform"},
        {"lang": "en-us", "value": "XMP - Extensible Metadata Platform"},
        {"lang": "fr-fr", "value": "XMP - Une Platforme Extensible pour les Métadonnées"},
        {"lang": "it-it", "value": "XMP - Piattaforma Estendibile di Metadata"}
    ]
}
```

XMP doesn't provide a binary encoding, which feels like a big limitation for 3D Tiles and glTF. I could imagine defining something based on [CBOR Typed Arrays](https://www.rfc-editor.org/rfc/rfc8746.html#name-typed-arrays), [Protocol Buffers](https://developers.google.com/protocol-buffers), [Flat Buffers](https://google.github.io/flatbuffers/), or similar efforts. These are mature enough — at least _as libraries_ — but I'm less sure whether they're appropriate for use in standards.

**Comment by pjcozzi** [comment]
I think this issue is now duplicate with:
* 3D Tiles Next Metadata and XMP #554
* Spatial subdivision within a glTF model #553
* Spatial subdivision for USD #555

Solving the later two (or just one) should also answer how 3D Tiles implicit/explicit tiling can be decoupled from 3D Tiles in general.

@ptrgags @donmccurdy please comment in those issue if there is anything of substance here that would be better served in any of those issues. 🙏
