### ISSUE TITLE
Units in Metadata Semantic Reference

### ISSUE THREAD

**Issue by donmccurdy** [CesiumGS/3d-tiles#520]
The [Metadata Semantic Reference](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/specification/Metadata/Semantics) lists built-in semantics but does not mention units. I can imagine those could be inferred from the [Coordinate Reference System](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/specification#coordinate-reference-system-crs) section of the main spec. Or was the intention to provide semantic meaning _only_ and leave the units abstract? 

Semantics can be referred to elsewhere (e.g. EXT_mesh_features in glTF) so it may be helpful to be explicit about the units. But the only two built-in semantics relevant to glTF (ID and NAME) do not need units, so this isn't urgent.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles/pull/526
