### ISSUE TITLE
Add a property to specify the CRS of the tileset

### ISSUE THREAD

**Issue by jailln** [CesiumGS/3d-tiles#527]
Currently there is not property for declaring the CRS in which the tileset is.

We could add such a `crs` property to the `asset` class for instance?

Possibly related to #504

**Comment by lilleyse** [comment]
Let's keep the discussion in https://github.com/CesiumGS/3d-tiles/issues/504 for now - I renamed that issue to reflect the need for a CRS at the tileset level.
