### ISSUE TITLE
Metadata: ID, Name, and Description consistency

### ISSUE THREAD

**Issue by donmccurdy** [CesiumGS/3d-tiles#533]
*Continuing from https://github.com/CesiumGS/3d-tiles/pull/530/files#r739733458, comment from @lilleyse copied below:*

***

Enums, classes, and properties should each have an `id` property so that they can be uniquely identified within their scope. They should each have an optional `name` and `description` for consistency as well.

I was looking at `EXT_mesh_features` and here are the differences that I noticed. 

**Cesium 3D Metadata**

Concept|Has ID|Has Name|Has Description
--|--|--|--
Schema|:x:|:x:|:x:
Enum|:x:|:x:|:x:
Class|:heavy_check_mark:|:x:|:x:
Property|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:

**`EXT_mesh_features`**
Concept|Has ID|Has Name|Has Description
--|--|--|--
Schema|:x:|:heavy_check_mark:|:heavy_check_mark:
Enum|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
Class|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
Property|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:

The biggest thing missing here is schema `id` which would let us uniquely identify schemas in a global sense. We should probably add that to `EXT_mesh_features`, `3DTILES_metadata`, and here. Though I'm not sure if schema `id` should be required.

**Comment by donmccurdy** [comment]
Adding to the list:

**`3DTILES_metadata`**

Concept|Has ID|Has Name|Has Description
--|--|--|--
Schema|:x:|:heavy_check_mark:|:heavy_check_mark:
Enum|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
Class|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:
Property|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:

**Comment by donmccurdy** [comment]
> The biggest thing missing here is schema id which would let us uniquely identify schemas in a global sense.

Does `schema.id` conflict with `schema.version` at all? I.e. should a later version of a schema have the same ID as the original?

**Comment by lilleyse** [comment]
> Does `schema.id` conflict with `schema.version` at all? I.e. should a later version of a schema have the same ID as the original?

The way I'm envisioning it the ID would stay the same but the version would change (like a software library)

> Somewhat related, see #524 – we are removing `name` and `description` from tileset and content group definitions. Instead of `name` authors should use properties with the `NAME` semantic; there is currently no `DESCRIPTION` semantic.

Good call, we should add a `DESCRIPTION` semantic.

> It does look like 3DTILES_metadata and `EXT_mesh_features` are already aligned, so we should at least update the 3D Metadata spec to match that... an ID for schema is OK with me too but would be a new addition for all three.

Yes we should add it to all three documents.

**Comment by donmccurdy** [comment]
Proposed changes for Core Metadata and 3DTILES_metadata in https://github.com/CesiumGS/3d-tiles/pull/539.

**Comment by donmccurdy** [comment]
Proposed `DESCRIPTION` semantic in https://github.com/CesiumGS/3d-tiles/pull/540.
