### ISSUE TITLE
Too many features IDs in feature ID texture

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#544]
I'm running into a situation where I have 392 features in a single tile and I can't encode them in single channel of an 8-bit PNG texture.

Original texture using RGB values to distinguish features|Feature ID texture. Middle gray = exceeded bit depth
--|--
![0aa_img0](https://user-images.githubusercontent.com/915398/140672405-f9cbb6cc-3877-4a5d-beef-7094cb1e65c6.png)|![0a_img1](https://user-images.githubusercontent.com/915398/140672475-b5f44bec-c7dd-4570-9d15-00eb89b61a7f.png)

There are a few options here:

* Use higher bit depth images like 16-bit PNGs or 16-bit KTX2 and upload this to the GPU with a large enough `internalFormat`
* Allow a feature id texture to have multiple channels. For typical 8-bit 4-channel PNGs this gives us 2^32 unique features
* Add a `color -> feature id` table to the spec

I prefer the second option since it requires minimal spec changes and lets us continue to use common image formats.

**Comment by donmccurdy** [comment]
Possible overlap with https://github.com/CesiumGS/3d-tiles/issues/265 – if we're going to recommend that global IDs be stored in Property Tables and Property Textures, do we also need to allow property values to span multiple channels of a texture for 16-bit and 32-bit types?

**Comment by javagl** [comment]
The `EXT_mesh_features` extension now allows defining feature IDs in textures using an [array of `channels`](https://github.com/CesiumGS/glTF/blob/c38f7f37e894004353c15cd0481bc5b7381ce841/extensions/2.0/Vendor/EXT_mesh_features/schema/featureIdTexture.schema.json#L13). The [specification text](https://github.com/CesiumGS/glTF/blob/c38f7f37e894004353c15cd0481bc5b7381ce841/extensions/2.0/Vendor/EXT_mesh_features/README.md#feature-id-by-texture-coordinates) describes how to combine these channels into an (up to 32bit) feature ID.

The case of images where channels have _more_ than 8 bits is not addressed explicitly, but this can be tracked in a dedicated issue if necessary.
