### ISSUE TITLE
3DTILES_implicit_tiling: Availability Buffer Endianness

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/3d-tiles#547]
Pictures like [this one](https://github.com/CesiumGS/3d-tiles/blob/main/extensions/3DTILES_implicit_tiling/figures/child-subtree-availability.jpg) in the implicit tiling spec are slightly misleading in that the availability bits appear in order (i.e., it appears to be big-endian). An extra warning or clarification about the actual little-endianness following those set of pictures may prevent some confusion. Since this is a bitstream (as opposed to a typed buffer or even bytestream), the endianness actually matters in this case since client implementations will need to create a way to access specific bits within a byte.

**Comment by javagl** [comment]
The [Subtree File Format](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#subtree-file-format) section mentions

> Subtrees are stored in little-endian. 

But I agree that this could be pointed out near the diagams, or clarified by adding an "Index in bitstream", similar to this image:

![Cesium Availability](https://user-images.githubusercontent.com/5597569/141509281-955e3dd3-9036-4d36-83a5-f3764a087e18.png)

**Comment by javagl** [comment]
The extension became core in 1.1 and is therefore finalized. It _does_ contain the information about endianness. We may consider pointing that out more prominently or changing the images for future versions, but until now, it did nto seem to cause any confusion, so I'll close that for now.
