### ISSUE TITLE
3D Tiles Next logo - grab and go access for the developer community

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#561]
There is a logo pack for 3D Tiles Next by the talented @argallegos: [3D-Tiles-Next-Logo.zip](https://github.com/CesiumGS/3d-tiles/files/7534346/3D-Tiles-Next-Logo.zip) 

I'd like to make these available under the same usage terms of the [official Cesium logos](https://cesium.com/press) for the developer community so they can include in presentations, GitHub repos, etc. - but this logo should not be for mainstream use since the **Next** suffix will be replaced with a version, #556.

@lilleyse could you please post the logo pack (including an embedded image that is easy to right click to copy) to a reasonable place and include the usage (it is a one pager that might be in the download of the official logo packs)?  Perhaps the right place is the [3D Tiles Next README.md](https://github.com/CesiumGS/3d-tiles/blob/main/next/README.md)?

🙏

**Comment by javagl** [comment]
This is a detail, and it might not be utterly important, but during the creation of the 3D Tiles Next logo, the 3D Tiles logo was updated: In its original form (as it is contained in the logo pack), it contained some not-so-cleanly drawn lines that looked a bit odd when zooming in. The new version is drawn a bit more precisely:

![Cesium Logo Zoom](https://user-images.githubusercontent.com/5597569/141847319-63e53c64-3e35-4234-97cb-b6aee69e73cd.png)

To go full pedantic mode, there now even is a "spec" for the logo:

![3DTiles-Logo-Specs-2021-11-07a](https://user-images.githubusercontent.com/5597569/141847453-9bc34fa3-d7c5-46b1-b5bd-6760f114932e.png)

Attaching this spec and the corresponding 3D Tiles (non-next) logo here, just for the case that it should be used in the logo pack at some point:

[3d-tiles-logo-and-specs-2021-11-15.zip](https://github.com/CesiumGS/3d-tiles/files/7541398/3d-tiles-logo-and-specs-2021-11-15.zip)
