### ISSUE TITLE
Use a white background for logos in READMEs

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/3d-tiles#564]
When you use dark mode, the 3D Tiles logo is hard to read:

![image](https://user-images.githubusercontent.com/8422414/141791826-dc8273f7-1c87-41e3-8889-fb51b49cf042.png)

the 3D Tiles Next logo has a similar issue.

The easiest thing is to use a logo with a white background in the README.

**Comment by javagl** [comment]
This is handled now with some GitHub trickery in the main `README.md`, which says
```
![](figures/3DTiles_light_color_small.png#gh-dark-mode-only)![](figures/3DTiles_dark_color_small.png#gh-light-mode-only)
```

![Cesium Logo Color](https://github.com/CesiumGS/3d-tiles/assets/5597569/de7c809e-87d0-4ace-ae2d-9188dc7bff81)
