### ISSUE TITLE
Convert geographical data to 3D Tiles Next

### ISSUE THREAD

**Issue by adam314315** [CesiumGS/3d-tiles#599]
Hi,

Currently using Cesium.js with 3D tilesets to generate building I am looking for a tool or process to convert geographical data (SHP for instance) to 3D Tiles Next format  (as presented here https://github.com/CesiumGS/3d-tiles/blob/main/specification/README.md)  to avoid having a large tileset.json files and split into smaller tileset.jon files attached to their corresponding bounding boxes. My current implementation with a single tileset.jon file works fine for a limited area but would require a too large single tileset.json file for a region, a country, etc.

**Comment by lilleyse** [comment]
Hi @adam314315, how are you generating your tileset.json today? To my knowledge there aren't any tools yet for creating tilesets with the [3DTILES_implicit_tiling](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling) extension so you may need to write your own pipeline. You should expect to see more tools for generating 3D Tiles Next as we go into next year.
