### ISSUE TITLE
Which method calls b3dm? It's function cesium3dtile()

### ISSUE THREAD

**Issue by bianbian886** [CesiumGS/3d-tiles#610]
Q1:I want to call b3dm directly, not through tileset.json. such as url : http://localhost:9528/static/3dtile/GWhite/1/1/0.b3dm?
Q2: in Vue through the import method,such as ：import Cesium3DTileset from "../../../public/static/cesium/Source/Scene/Cesium3DTileset"; then , new Cesium3DTileset({
      url: "./static/3dtile/GWhite1/tileset.json",
    });  It is added to the scene.primitives through the add method, and the model is not displayed

**Comment by lilleyse** [comment]
It's not possible to load a single b3dm by itself in CesiumJS. Are you able to load a glTF instead?

If you have follow up questions please ask them on the Cesium Community Forum: https://community.cesium.com/. We use this github repo for 3D Tiles spec discussion.
