### ISSUE TITLE
For 3dtiles without textures

### ISSUE THREAD

**Issue by xuebingzzz** [CesiumGS/3d-tiles#625]
If 3dtiles has no texture and no texture coordinates, how to add texture coordinates to it?

**Comment by lilleyse** [comment]
Usually texture coordinates are generated when the tileset is produced and can't be added very easily after the fact. How are your 3D Tiles being generated? And what are you trying to achieve by generating texture coordinates?

One case where texture coordinates are generated dynamically is for draping imagery layers over 3D Tiles in [cesium-native](https://github.com/CesiumGS/cesium-native), but I can't think of other cases right now.

**Comment by donmccurdy** [comment]
(/cc https://github.com/KhronosGroup/glTF/issues/2122)

**Comment by xuebingzzz** [comment]
The idea now is to add textures to 3dfiles
