### ISSUE TITLE
How to create uniform variables and use them in custom shader in 3D Tiles Next implementation? 

### ISSUE THREAD

**Issue by waterpeach** [CesiumGS/3d-tiles#626]

**Comment by ptrgags** [comment]
Hi @waterpeach,

CesiumJS implementation support questions should be directed to the [community forum](https://community.cesium.com/). This repo is for questions about the 3D Tiles Specification.

Though this question has a quick answer, see [This Sandcastle](https://sandcastle.cesium.com/?src=Custom%20Shaders%20Models.html&label=3D%20Tiles%20Next) for examples, and the [Custom Shader Guide](https://github.com/CesiumGS/cesium/tree/main/Documentation/CustomShaderGuide)
