### ISSUE TITLE
Specification of MIME Types (Media Types) in 3D Tiles

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles#639]
This is related to https://github.com/CesiumGS/3d-tiles/issues/341 . 

This is an attempt to collect the information about media types and file extensions for 3D Tiles, which could go into the specification at some point. (This information is already available to some extent, but summarized and extended here). 

### File Extensions and Media Types

- For the [3D tiles core](https://github.com/CesiumGS/3d-tiles/tree/main/specification) specification:

  - [Tileset JSON](https://github.com/CesiumGS/3d-tiles/tree/main/specification#tileset-json) files should use the `.json` extension and the [`application/json`](https://www.iana.org/assignments/media-types/application/json) Media Type.
  - [Tileset Style JSON](https://github.com/CesiumGS/3d-tiles/tree/main/specification/Styling) files should use the `.json` extension and the [`application/json`](https://www.iana.org/assignments/media-types/application/json) Media Type.
 
  - Tile Formats: 
    - [Batched 3D Models](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/Batched3DModel) should use the the `.b3dm` extension and the [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type. 
    - [Composite](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/Composite) Tiles should use the the `.cmpt` extension and the [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type. 
    - [Instanced 3D Models](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/Instanced3DModel) should use the the `.i3dm` extension and the [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type. 
    - [Point Clouds](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/PointCloud) should use the the `.pnts` extension and the [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type. 

- For the [3DTILES_implicit_tiling](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling) extension:
  - [Subtree JSON](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#subtree-json-format) files should use the `.json` extension and the [`application/json`](https://www.iana.org/assignments/media-types/application/json) Media Type.
  - [Subtree Binary](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#subtree-binary-format) files should use the `.subtree` extension, and the [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type.

- For the [3DTILES_metadata](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata) extension:
  - [Schema JSON](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_metadata#schema) files that are referred to via the `schemaUri` should use the `.json` extension, and the [`application/json`](https://www.iana.org/assignments/media-types/application/json) Media Type.

- For the [`3DTILES_content_gltf`](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf) extension: 
  - The glTF files that may be used as the tile content should follow the [glTF 2.0 Specification](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#file-extensions-and-media-types). This also refers to the files that are referenced by glTF files, namely binary buffers and image files.

- [Quantized Mesh](https://github.com/CesiumGS/quantized-mesh/blob/main/README.md) - TODO
 
---

In the definitions above, "should" means "SHOULD" as in https://www.rfc-editor.org/info/bcp14. Specifically: File extensions are generally considered to be _optional_. But without any file extension and explicit MIME type determination, it can be hard to differentiate between a Tileset JSON and a glTF JSON, for example (see https://github.com/CesiumGS/3d-tiles/issues/341#issuecomment-970331872 for related discussion). The implicit tiling specification originally defined a `mimeType` field for the `conetnt`, but this has [been removed at some point](https://github.com/CesiumGS/3d-tiles/pull/444/commits/d2d21d4bf1cbdad15d0fc59ef97fdb932d457f87). Some related discussion about determining the type of image data (and all the options and caveats) can be found in https://github.com/KhronosGroup/glTF/issues/1966 . 

A related question is whether there should be efforts to officially register certain MIME types for 3D Tiles, but this might better fit into https://github.com/CesiumGS/3d-tiles/issues/341 .

**Comment by lilleyse** [comment]
>   - [Tileset JSON](https://github.com/CesiumGS/3d-tiles/tree/main/specification#tileset-json) files should use the `.tileset` extension and the [`application/json`](https://www.iana.org/assignments/media-types/application/json) Media Type.

`"tileset.json"` is so ubiquitous at this point that I think the recommended extension should stay `.json`.

The subtree file extension should probably be `.json` as well.

> [Subtree Binary](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#subtree-binary-format) files should use the .subtree extension, and the [application/octet-stream](https://www.iana.org/assignments/media-types/application/octet-stream) Media Type.

Or `.subt` if we want something shorter

> [Quantized Mesh](https://github.com/CesiumGS/quantized-mesh/blob/main/README.md) - TODO

Probably out of scope for this

**Comment by lilleyse** [comment]
Until we've officially registered media types there's also the option of using vendor prefixes, e.g. `application/vnd.3dtiles.tileset+json`, `application/vnd.3dtiles.subtree+json`,`application/vnd.3dtiles.schema+json`

**Comment by javagl** [comment]
Sorry, the `.tileset` was a Copy+Paste error (I shouldn't have submitted it without proofreading, despite the call 2 minutes later...). 

I had seen the use of the `vnd.` prefix for `vnd.quantized-mesh`, but wasn't sure whether there are plans for registering MIME types.

Also, the question of whether the MIME types are supposed to be encoded in some `content { mimeType: "...", ... }` property demains to be decided.

**Comment by javagl** [comment]
The 3D Tiles 1.1 specification contains a section that summarizes the MIME types (Media Types). And it generally says that one should not rely on file extensions. Further clarifications or additions (like a `mimeType` property in `content` objects and such) would be a change that could go into the next version.
