### ISSUE TITLE
Consider combining `normalized/offset/scale` in `valueTransform`

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles#650]
A [class property](https://github.com/CesiumGS/3d-tiles/tree/5367720a417d7741b0f613fd29d0a584990a6548/specification/Metadata#property) can have the following properties:

- name, description *(metadata)*
- type, componentType, enumType, array, count *(structure)*
- normalized, offset, scale *(value transform)*
- required, noData, default *(usage)*
- max, min *("value metadata"?)*
- semantic *("usage metadata"?)*

The grouping of these properties in the list above _roughly_ corresponds to what I'd consider as "things that belong together", with "the thing that they represent" given in brackets. One could go very far with listing options about how these things could be modeled and represented. But one consideration is to combine the `normalized`, `offset` and `scale` properties into a single thing. This single thing could be called `valueTransform`. 

---

An aside: 

There are many trade-offs and considerations when it comes to the question about how to actually _model_ things like this. This refers to the _implementation_ (e.g. the JSON schema in `3DTILES_metadata`). There sometimes are requirements or constraints that are only described _verbally_, in the _description_ in the JSON schema, but hard to check _structurally_. And one of these requirements here is that `offset` and `scale` may only be present when `normalized` is `true`. One way of modeling this "value transform" _structurally_ would be to ditch the `normalized` flag, and just say that the `offset` and `scale` of the `valueTransform` indicate the [codomain](https://en.wikipedia.org/wiki/Codomain) of the value transformation, defaulting to `offset=0,scale=1`. Then, the presence of an (empty!) `valueTransform: {}` is the same as `normalized=true`. A structure like
```
valueTransform: {
    offset: 10,
    scale: 20
}
```
would map the source range of the value (whatever that is) to the range [10,20]. In any case, it would no longer technically be possible to have invalid structures with things like `normalized=false,scale=10`. 

Would that be "better"? In some ways, and a technical sense: Yes. Would it be "nicer", along all the possible dimensions of the term 'nice'? That's open for debate.

**Comment by lilleyse** [comment]
> And one of these requirements here is that `offset` and `scale` may only be present when `normalized` is `true`. 

`offset` and `scale` can also apply to `FLOAT32` and `FLOAT64` component types.

**Comment by javagl** [comment]
While I still think that combining things that belong together and giving _names_ to these things is the right approach (and such a `ValueTransform` could have made sense), the 3D Tiles 1.1 specification is finalized in its current form, so I'm closing this for now.
