### ISSUE TITLE
EXCEPTION! Specified argument was out of the range of valid values 

### ISSUE THREAD

**Issue by JCAELA** [CesiumGS/3d-tiles#702]
While running the full pipeline of Obj2Tiles I get the "Specified argument was out of the range of valid values" exception.
Does anyone know what causes it and how to solve it?

Thank you

![exceptionss](https://user-images.githubusercontent.com/100201026/176732448-3aaa9cb7-808d-46b8-a40f-b1dd10e38d97.PNG)

**Comment by lilleyse** [comment]
Hi @JCAELA, Cesium doesn't maintain Obj2Tiles, you may have better luck opening an issue there: https://github.com/OpenDroneMap/Obj2Tiles
