### ISSUE TITLE
artifact while rendering 3d tiles in the cesium viewer

### ISSUE THREAD

**Issue by deven-gqc** [CesiumGS/3d-tiles#713]
Hello,

I have an asset uploaded on Cesium Ion which is causing a rendering artifact. When I zoom into the map to a certain extent, the rendered 3d tiles show up, the moment I zoom in even more, the 3d tile disappears.

Before zooming in
![image](https://user-images.githubusercontent.com/86305049/189992827-003e3533-5c5d-4d67-b613-8030ca569ddc.png)

After zooming in
![image](https://user-images.githubusercontent.com/86305049/189992914-db8c0645-036c-48be-a46a-788c849e8462.png)

Can anyone help me with this? TIA

**Comment by lilleyse** [comment]
@deven-gqc we might need more information to triage this, such as the asset ID and CesiumJS version. Could you create a post on the [Cesium Community Forum](https://community.cesium.com/)? I'm going to close this issue and we can continue the discussion there.

**Comment by deven-gqc** [comment]
@lilleyse I've created a post in the community forums over here, [Link](https://community.cesium.com/t/artifact-while-rendering-3d-tiles-in-the-cesium-viewer/20370)
