### ISSUE TITLE
about 3dtile_next example

### ISSUE THREAD

**Issue by bb67ao** [CesiumGS/3d-tiles#714]
could you please share the data of the 3d_tile_next photogrammetry classification,really appreciate

**Comment by lilleyse** [comment]
@bb67ao I'm not sure if we'll be able to share the tileset as a download, but you should be able to stream it from ion.

If you're looking for smaller datasets that use the same capabilities check out https://github.com/CesiumGS/3d-tiles-samples/tree/main/glTF
