### ISSUE TITLE
3DTILES_multiple_content can't load and render more than six tiles

### ISSUE THREAD

**Issue by Iron-john** [CesiumGS/3d-tiles#723]
Hi threre!
Thanks for the excellent update of 3DTiles next! 
There is a building model which is divided into 8 glb tiles, and I want to add and render the model by 3DTILES_multiple_content. But I falied, founding that when the number of tiles is over 6 in tileset.json, all the tiles can't be loaded and rendered. I wonder if this is an error in my data organization or some limits of Cesium?  There are two kinds of content of my multiple_content tileset.json as follows.   
![image](https://user-images.githubusercontent.com/73344864/203494249-1dd1de85-5ca5-472a-ace9-5f09622236de.png)
![image](https://user-images.githubusercontent.com/73344864/203494577-3b0e7900-d074-4347-8ee2-282fbde13bc8.png)

**Comment by lilleyse** [comment]
Hi @Iron-john - this is a CesiumJS limitation. See https://github.com/CesiumGS/cesium/issues/10468.
