### ISSUE TITLE
Clarification: how do OGC 3D Tiles relate to OGC Tiles? 

### ISSUE THREAD

**Issue by AndrewAnnex** [CesiumGS/3d-tiles#734]
Currently the OGC is developing the OGC Tiles API that uses TileMatrixSets to define grid based indexes for vector and raster data. Are there any plans to adopt OGC TileMatrixSets to more closely align  "3D-Tiles" to "OGC Tiles"? 

the naming of these things is a little confusing so forgive me if this is already in the works.

**Comment by jerstlouis** [comment]
@AndrewAnnex 

Thank you for bringing this up.
There is a section in 2DTMS https://docs.opengeospatial.org/is/17-083r4/17-083r4.html#toc88 discussing the relationship.

I filed these 4 issues to try to bridge the remaining gaps: #586 #587 #588 #589

As discussed with @lilleyse , this might be something addressed in a future version.

**Comment by javagl** [comment]
If the linked section in the specification does not sufficiently answer the question, feel free to reopen this and ask for further details.
