### ISSUE TITLE
Maybe spell error

### ISSUE THREAD

**Issue by ScienceGeekxx** [CesiumGS/3d-tiles#747]
![image](https://github.com/CesiumGS/3d-tiles/assets/13169194/8bc2a63b-ed9a-46aa-9aa1-22dd66ecb7ba)
Maybe "de" is "be".
https://docs.ogc.org/cs/22-025r4/22-025r4.html#toc24

**Comment by javagl** [comment]
Indeed spell error. Thanks, the fix is in https://github.com/CesiumGS/3d-tiles/pull/749
