### ISSUE TITLE
3D-Tiles 1.1 Implicit tile about .subtree binary file

### ISSUE THREAD

**Issue by cjhdsg** [CesiumGS/3d-tiles#765]
I am currently working on implementing implicit tiles in 3D-Tiles version 1.1 using C++, specifically focusing on the .subtree binary files. These files contain binary chunk representing tile availability. I am seeking clarification on the data type (int, short, char, or others) used for storing this availability information.

Could you please provide insights into the data type utilized for storing tile availability in the binary section of .subtree files? Understanding this aspect is crucial for ensuring accurate interpretation and manipulation of the data.

Your guidance on this matter would be greatly appreciated.

**Comment by cjhdsg** [comment]
I've just understood the each tile's availability is stored in bits instead of bytes, and 8 bits are converted to bytes and stored in the .subtree files. 

The crux of my confusion lies in how individual bits are organized and packed into bytes. I have attempted to perform numerical conversion, but it seems that the results do not align with the expected byte representation.

Could you please provide detailed insights into the process of converting bits to bytes for storing tile availability? Understanding this process is crucial for me to correctly interpret and manipulate the availability data.

Any guidance or clarification on this matter would be greatly appreciated.

Thank you for your assistance!

![issue](https://github.com/CesiumGS/3d-tiles/assets/74944117/cb39b266-30e2-45a3-88b3-73278329fa68)

**Comment by cjhdsg** [comment]
I have recently observed an interesting correlation when reversing an 8-bit sequence, such as "10110000", which results in "00001101". Remarkably, the hexadecimal representation of the reversed sequence is "0x0d", which aligns with the expected byte representation. I am curious to know whether this is merely a coincidence or if there is a deeper underlying principle at play.

Could you please provide insights into whether there is a fundamental relationship or principle that explains this phenomenon?

Thank you for your assistance in exploring this intriguing observation.

**Comment by GatorScott** [comment]
[Endianness](https://en.wikipedia.org/wiki/Endianness).

**Comment by javagl** [comment]
The term _endianness_ usually refers to the order of _bytes_ within a multi-byte type. Here, the question is about the order of _bits_ within a _byte_.

> I have recently observed an interesting correlation when reversing an 8-bit sequence, such as "10110000", which results in "00001101". Remarkably, the hexadecimal representation of the reversed sequence is "0x0d", which aligns with the expected byte representation. I am curious to know whether this is merely a coincidence or if there is a deeper underlying principle at play.

In the tables that are shown in that `subtreeInfo.md` (and that you showed in the screenshot), I did hesitate quite a while. I was afraid that _either_ bit order could be confusing, depending on the understanding or expectation that a reader might have. So I tried to resolve the ambiguity here, by explicitly saying
Bits **[0...7]** :
in the description.

Usually, when you show the bits of one byte, the order will be
`7 6 5 4 3 2 1 0`
In a byte with value `6`, the bits `2` and `1` will be set, meaning that it will usually be displayed as
`0 0 0 0 0 1 1 0`.

In the tables, the bits are shown with the order
`0 1 2 3 4 5 6 7`
(as indicated by the **[0...7]** part), meaning that the bits for a value of 6 will be
`0 1 1 0 0 0 0 0`.

Now you may ask **why** I did this. And the answer is that I tried to make these table rows more similar to the the images at https://github.com/CesiumGS/3d-tiles/tree/main/specification/ImplicitTiling#tile-availability , where the "Tile Availability" bitstream is shown _from left to right_ (i.e the bit with index 0 is shown at the _leftmost_ side)

When you take the bits from the tables, _in the order in which they are shown_, then they will be
`10110000 01001100 10000000` 
matching the order of the bits in these images.

**Comment by javagl** [comment]
The "**[0...7]**" part of the description was intended to make clear which bit order is used for the description. If this is confusing, then it _could_ be changed, but ... I wonder _how_ it should be changed. So unless there are specific requests for changes, I assume that there are no actionable items here.
