### ISSUE TITLE
3D-Tiles 1.1 voxel

### ISSUE THREAD

**Issue by cjhdsg** [CesiumGS/3d-tiles#768]
I am currently working with 3D-Tiles 1.1, specifically using 3DTILES_content_voxels and implicit tiles to handle voxel data. I have encountered an issue and would like to ask for some guidance: how can I control the rendering process to hide content that does not contain any voxels?

Specifically, when loading voxel data, some tiles are empty (i.e., they do not contain any voxel data). However, these empty tiles still appear as placeholders during rendering. This results in unnecessary content being displayed, which affects the final visualization.

I have correctly set the tile availability and content availability, which has been verified to work correctly with glb models. However, when switching to voxels, the content availability I set indicates no content at position 0/0/0/0. Despite this, the console reports a 404 error requesting 0.0.0.0.json, which should not be requested. After manually adding this file, only the voxels at position 0/0/0/0 are displayed.

Is there a way to prevent these unnecessary file requests and ensure that tiles without voxel data are not displayed during the loading or rendering stage? Any suggestions or solutions would be greatly appreciated. Thank you!

Looking forward to your responses.
![implicit tile glb](https://github.com/CesiumGS/3d-tiles/assets/74944117/2ca40522-1070-4029-8255-c7cb93342d70)
![implicit tile voxel](https://github.com/CesiumGS/3d-tiles/assets/74944117/d2b2a609-d8f3-461c-ac42-140e4c2dd4c8)
![implicit tile voxel-error](https://github.com/CesiumGS/3d-tiles/assets/74944117/d0ea4a14-9029-4a09-9fb5-33829b2d54b9)

**Comment by javagl** [comment]
This repository is for maintaining the specification of 3D Tiles. If you want to ask for clarifications about the _specification_, then this can be done by opening an issue here (even when the _goal_ is _implementing_ a 3D Tiles renderer based on the specification). But the issues here are not a general support area. If you have questions that are _only_ about an implementation or aspects of the behavior of CesiumJS in particular, you should ask them in the community forum at https://community.cesium.com/c/cesiumjs/5

In this case, it would probably be helpful if you could share that tileset, attached as a ZIP file (assuming that this is only test data that can be shared). Right now, I don't see why the _type_ of the content should determine whether ~"invalid requests" should be sent out. But maybe this can be sorted out in the forum thread.

**Comment by cjhdsg** [comment]
Of course, my test dataset is followed, which includes two tilesets. One uses implicit tile and glb extension, the other uses implicit tile and voxel extension, both of which have the same subtree files.
[test-dataset.zip](https://github.com/CesiumGS/3d-tiles/files/15350387/test-dataset.zip)
