### ISSUE TITLE
pointSize styling doesn't work for gltf using EXT_mesh_features and EXT_structural_metadata

### ISSUE THREAD

**Issue by MrSmallLiu** [CesiumGS/3d-tiles#784]
pointSize styling doesn't work for gltf using EXT_mesh_features and EXT_structural_metadata  

tileset.style = new Cesium.Cesium3DTileStyle({
    show: true,
    color: 'color("green", 0.5)',
    pointSize: 10,
  });

**Comment by javagl** [comment]
This is not an issue of the 3D Tiles format itself, but rather of CesiumJS. Closing in favor of https://github.com/CesiumGS/cesium/issues/12398 (and I'll post additional details there)
