### ISSUE TITLE
3D Tiles reference card

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles#93]
Like [glTF](https://github.com/javagl/gltfOverview).

**Comment by ggetz** [comment]
As a starting point, here's a UML diagram  by IGF - ![3dtilesuml](https://user-images.githubusercontent.com/4439461/48445450-9e193c80-e764-11e8-97b7-c6de590d0811.jpg)

**Comment by pjcozzi** [comment]
Related:

![image](https://user-images.githubusercontent.com/782098/64080742-d1ae5e80-ccc5-11e9-893d-683d09f84162.png)

and

![image](https://user-images.githubusercontent.com/782098/64080746-e1c63e00-ccc5-11e9-9b37-4ab4e93f1669.png)

**Comment by pjcozzi** [comment]
Also:

![image](https://user-images.githubusercontent.com/782098/64123275-ef390200-cd71-11e9-9084-38eeb8e6cb9a.png)

**Comment by pjcozzi** [comment]
Reference card: https://github.com/CesiumGS/3d-tiles/tree/master/overview

Hopefully more to come for 3D Tiles extensions.
